'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'ml' | 'kn'

const SUPPORTED_LANGUAGES: Language[] = ['en', 'hi', 'ta', 'te', 'ml', 'kn']

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  supportedLanguages: Language[]
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About us',
    'nav.emi': 'EMI Calculator',
    'nav.apply': 'Apply Now',
    'nav.cibil': 'Cibil Score',
    'nav.contact': 'Talk to an Expert',
    'nav.instantApproval': 'Instant Loan',
    'nav.talkToExpert': 'Talk to Expert',
    'nav.partner': 'Become a Partner',
    'nav.login': 'Login',

    // Partner Page
    'partner.title': 'Become a Partner',
    'partner.titlePrefix': 'Become a ',
    'partner.titleHighlight': 'Partner',
    'partner.titleSuffix': '',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'Join our network of loan providers and grow your business.',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'Your Name',
    'partner.labelFullName': 'Full name',
    'partner.companyName': 'Company Name',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.email': 'Email Address',
    'partner.labelWorkEmail': 'Work email',
    'partner.phone': 'Phone Number',
    'partner.labelPhone': 'Contact number',
    'partner.city': 'City',
    'partner.labelCity': 'City',
    'partner.message': 'Message',
    'partner.labelTellUsMore': 'How do you want to partner? (e.g. referrals, distribution, tie-up)',
    'partner.submit': 'Submit Request',
    'partner.submitting': 'Submitting...',
    'partner.success': 'Application submitted successfully! We will contact you soon.',
    'partner.error': 'Something went wrong. Please try again.',
    'partner.benefitsHeading': 'Why partner with us?',
    'partner.benefit1': 'Access to a wide range of loan products and lenders',
    'partner.benefit2': 'Dedicated support and training for your team',
    'partner.benefit3': 'Competitive commissions and timely payouts',
    'partner.benefit4': 'Marketing and lead generation support',
    'partner.benefit5': 'Grow your business with a trusted brand',


    // Language switcher
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',

    // Hero
    'hero.title': 'Providing the best future for your best living.',
    'hero.highlight': 'best',
    'hero.titleLine1': 'Providing the best future',
    'hero.titleLine2': 'for your best living.',

    // Features
    'features.offer1Title': '₹2100 Cashback',
    'features.offer1Desc': 'Get Cashback of ₹2100 Above 20 lakh loan Amount',
    'features.offer1BackLine1': '20th to 22nd MARCH',
    'features.offer1BackLine2': 'T&C*',
    'features.offer2Title': '₹3100 Cashback',
    'features.offer2Desc': '₹3100 – On loans above ₹25 Lakh (Bajaj PL/OD)',
    'features.offer2BackLine1': '20th to 22nd MARCH',
    'features.offer2BackLine2': 'T&C*',
    'features.promiseTitle': 'Helloans Promise',
    'features.promiseDesc': '(To Provide the Cashback on time) Quick disbursal & Low Roi',
    'features.promiseBackLine1': 'Terms & conditions apply',
    'features.promiseBackLine2': 'T&C*',

    // Carousel
    'carousel.instantLoan': 'Instant Loan',
    'carousel.instantLoanDesc': 'A convenient and speedy way to get the funds you require for unanticipated expenses.',
    'carousel.overdraft': 'Overdraft',
    'carousel.personalLoans': 'Personal Loans',
    'carousel.personalLoansDesc': 'Whether it\'s for debt repayment or big life ambitions, a personal loan can be an excellent financial instrument.',
    'carousel.businessLoans': 'Business Loans',
    'carousel.businessLoansDesc': 'Business loan enables you to expand your business and network. It provides financial stability in your business.',
    'carousel.professionalLoans': 'Professional Loans',
    'carousel.professionalLoansDesc': 'A professional loan is a type of funding meant for professionals, such as accountants and attorneys.',
    'carousel.secureLoans': 'Secure Loans',
    'carousel.secureLoansDesc': 'With a secured loan, you\'re eligible for low interest rates since property is pledged as security.',
    'carousel.balanceTransfer': 'Balance Transfer',
    'carousel.balanceTransferDesc': 'Transfer your existing loan to us and save on interest rates with better terms and conditions.',
    'carousel.homeLoans': 'Home Loans',
    'carousel.goldLoans': 'Gold Loans',
    'carousel.educationLoans': 'Education Loans',
    'carousel.insurance': 'Insurance',
    'carousel.creditCards': 'Credit Cards',
    'carousel.applyNow': 'Apply Now',
    'carousel.viewAll': 'View All',

    // Loan Tiles Section
    'loanTiles.title': 'Our Loan Products',

    // Trust Section
    'trust.title': 'Trust with',
    'trust.titleHighlight': 'Confidence',
    'trust.loansDisbursed': '₹ 15000 Crore+',
    'trust.loansDisbursedDesc': 'Worth of loans disbursed to our users',
    'trust.since2016': 'Since 2016',
    'trust.since2016Desc': '13 years of customers love and trust',
    'trust.panIndia': 'Pan India',
    'trust.panIndiaDesc': 'Serving you, wherever you are',
    'trust.iso27001': 'ISO 27001',
    'trust.iso27001Desc': 'Certified Data Security Excellence',

    // Testimonials
    'testimonials.happyClients': '12K + Happy Clients',
    'testimonials.title': 'Client Experiences',
    'testimonials.readAll': 'Read All Review →',
    'testimonials.rating': 'Rating',

    // Partners
    'partners.title': 'Our Authorized Partners',

    // Footer
    'footer.tagline': 'Fastest Way To Get Money',
    'footer.description': 'Our team of experienced professionals is dedicated to providing competitive interest rates, flexible repayment options, and a hassle-free application process.',
    'footer.quickLinks': 'Quick Links',
    'footer.getInTouch': 'Get in touch',
    'footer.socialMedia': 'Social Media Links',
    'footer.copyright': '© Copyright 2026 | HELLOANS ZINEE SERVICES PVT LTD (Formerly a part of ZINEE GROUP)',

    // Talk to an Expert Page
    'expert.title': 'Talk to an Expert',
    'expert.subtitle': 'Get personalized loan advice in real time. No forms, no wait—just chat.',
    'expert.liveHelp': 'Live help available',
    'expert.cta': 'Start chatting in the panel on the right →',
    'expert.helpHeading': 'We can help with',
    'expert.bullet1': 'Loan types & best options for you',
    'expert.bullet2': 'Eligibility & documentation help',
    'expert.bullet3': 'Instant answers to your questions',
    'expert.emailLabel': 'Prefer email?',
    'expert.email': 'info@zineegroup.com',
    'expert.phoneLabel': 'Call us',
    'expert.chatLabel': 'Chat',

    // Contact (legacy / shared)
    'contact.getInTouch': 'Get in Touch',
    'contact.talkToExpert': 'Talk to an Expert',
    'contact.chatbotIntro': 'Have questions about loans or need personalized advice? Start a chat with our expert—no form needed.',
    'contact.chatbotDesc': 'Our chatbot can help you with loan types, eligibility, documents, and connect you to the team.',
    'contact.startChat': 'Start chat',
    'contact.socialMedia': 'Social Media Links',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.phone': 'Phone No.',
    'contact.message': 'Message',
    'contact.submit': 'Submit Now',
    'contact.submitting': 'Submitting...',
    'contact.success': 'Success! Your message has been sent. We will contact you soon.',
    'contact.error': 'There was an error sending your message. Please try again.',

    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Redefining Financial Excellence for SMEs & Professionals!',
    'about.learnMore': 'Learn More →',
    'about.gallery': 'Gallery',
    'about.intro1': 'Welcome to Helloans Zinee Services Pvt. Ltd. (Formerly a part of ZINEE GROUP). At HELLOANS, we deliver bespoke financial solutions crafted to empower India\'s small and medium enterprises, salaried personnel & professionals. Leveraging cutting-edge analytics and deep market expertise, we simplify complex loan landscapes and optimize borrowing strategies to secure the best terms with complete transparency.',
    'about.intro2': 'Our comprehensive suite of services spans home, business and personal loan advisory, proprietary EMI optimization models, credit enhancement strategies and advanced financial literacy programs. HELLOANS is committed to integrity, innovation and excellence. Partner with us to unlock smarter, hassle-free finance solutions that fuel your ambitions and safeguard your future.',
    'about.intro3': 'Get in touch today to experience a trusted advisor who puts your financial success first! 🧞‍♂️',
    'about.loanTypes': 'Unsecured & Secured Loans',
    'about.loanTypesSubtitle': 'We Are Providing All Types Loan.',
    'about.instantLoan': 'Instant Loan',
    'about.personalLoans': 'Personal Loans',
    'about.businessLoans': 'Business Loans',
    'about.professionalLoans': 'Professional Loans',
    'about.secureLoans': 'Secure Loans',
    'about.balanceTransfer': 'Balance Transfer',
    'about.whyChoose': 'Why Choose Us',
    'about.whyChooseSubtitle': 'Why you should choose Helloans, there are tons of reasons.',
    'about.whyChooseText': 'Leveraging cutting-edge analytics and deep market expertise, we simplify complex loan landscapes and optimize borrowing strategies.',
    'about.professionalService': 'Professional Service',
    'about.ultraFastSupport': 'Ultra Fast Support',
    'about.lowInterestLoan': 'Low Interest Loan',
    'about.available24x7': '24x7 Available',
    'about.ctaTitle': 'Looking For a Loan?',
    'about.ctaText': 'Partner with us to unlock smarter, hassle-free finance solutions!',
    'about.ctaDescription': 'Our team of experienced professionals is dedicated to providing competitive interest rates, flexible repayment options, and a hassle-free application process. Get in touch today!',

    // CIBIL Score Page
    'cibil.heroTitle': 'Check Your Free Credit Score Today!',
    'cibil.heroSubtitle': 'Check Your Free Credit Score Today!',
    'cibil.securityMessage': 'Your Personal Information is 100% secured with us. We do not share your data with any third party.',
    'cibil.whatIsCreditScore': 'What is a Credit Score?',
    'cibil.whatIsCreditScoreText1': 'Your credit score is an essential indicator of your financial reliability, serving as a measure of how well you manage and repay debts. Represented as a three-digit number typically ranging from 300 to 900, it reflects your creditworthiness and is calculated based on your credit history and data from various loan types and credit bureaus. This score helps lenders and financial institutions assess your likelihood of repaying borrowed money on time.',
    'cibil.whatIsCreditScoreText2': 'A higher credit score, generally considered good if it exceeds 700, improves your chances of loan approval and securing better interest rates. In India, the most commonly recognized credit score is the CIBIL Score, provided by TransUnion. Other credit bureaus, including Experian, CRIF High Mark, and Equifax, also contribute by collecting and analyzing your credit information to generate your score. Factors like repayment history, types of loans, credit utilization, credit history length, and the frequency of credit applications influence your score.',
    'cibil.creditScoreRange': 'What is the range of the Credit Score?',
    'cibil.creditScoreRangeText': 'Credit scores, though slightly varying across bureaus, typically range from 300 (lowest) to 900 (highest). If you have no credit history, you\'ll need to build it by responsibly using credit cards or loans. Here\'s an overview of credit score ranges and their implications:',
    'cibil.badCredit': 'Bad Credit',
    'cibil.badCreditRange': '300-549',
    'cibil.badCreditDesc': 'Indicates missed payments, defaults, or high credit utilization. It makes securing loans or credit cards difficult and often leads to unfavorable terms.',
    'cibil.poorCredit': 'Poor Credit',
    'cibil.poorCreditRange': '550-649',
    'cibil.poorCreditDesc': 'Suggests some repayment issues, which may limit loan approvals or result in less favorable conditions.',
    'cibil.fairCredit': 'Fair Credit',
    'cibil.fairCreditRange': '650-749',
    'cibil.fairCreditDesc': 'Reflects a responsible repayment history, improving chances of loan approval but not necessarily with the best interest rates.',
    'cibil.goodCredit': 'Good Credit',
    'cibil.goodCreditRange': '750-799',
    'cibil.goodCreditDesc': 'Represents consistent on-time payments and sound credit management, increasing the likelihood of loan approval with favorable terms.',
    'cibil.excellentCredit': 'Excellent Credit',
    'cibil.excellentCreditRange': '800-900',
    'cibil.excellentCreditDesc': 'Demonstrates exceptional financial management, offering the best opportunities for loans and credit cards with the most attractive rates and terms.',
    'cibil.benefitsTitle': 'Benefits of Good credit score',
    'cibil.benefitsText1': 'Your credit score is a crucial measure of your financial well-being and plays a significant role in determining your loan and credit card options. A high credit score, typically above 700, comes with numerous advantages. It boosts your chances of loan approval, qualifies you for lower interest rates, and helps you save money.',
    'cibil.benefitsText2': 'A strong credit score also provides access to pre-approved loans with quicker processing and exclusive credit cards that offer premium rewards. Additionally, it can make you eligible for higher credit limits and longer loan repayment terms, offering greater flexibility and reducing financial stress. Maintaining a good credit score opens doors to better credit opportunities and paves the way for a secure financial future.',
    'cibil.buildCreditTitle': 'What Is the Fastest Way to Build Credit?',
    'cibil.buildCreditText': 'Building a strong credit score unlocks numerous financial opportunities, but starting from scratch can feel challenging. The good news is that establishing credit is entirely achievable! Responsible credit use is the fastest way to build your score. Getting a credit card in your name is a great first step. Once you have one, consistently making on-time payments is crucial to creating a positive payment history, a key factor in building a good credit score. Regularly checking your credit report for errors that may harm your score is equally important. By following these steps, you\'ll be on the right path to a solid credit foundation.',
    'cibil.payOnTime': 'Pay on Time',
    'cibil.payOnTimeDesc': 'Always prioritize timely payments for all debts to maintain a good payment history.',
    'cibil.limitInquiries': 'Limit Inquiries',
    'cibil.limitInquiriesDesc': 'Avoid excessive credit applications, as too many inquiries can lower your score.',
    'cibil.payDownBalances': 'Pay Down Balances',
    'cibil.payDownBalancesDesc': 'Keep credit card balances low to improve your credit utilization ratio.',
    'cibil.consolidateDebt': 'Consolidate Debt',
    'cibil.consolidateDebtDesc': 'Use a consolidation loan to reduce credit utilization and simplify repayment.',
    'cibil.authorizedUser': 'Become an Authorized User',
    'cibil.authorizedUserDesc': 'Linking to someone\'s account with a strong payment history can boost your score (choose carefully).',
    'cibil.keepOldAccounts': 'Keep Old Accounts Open',
    'cibil.keepOldAccountsDesc': 'A longer credit history improves your score, so avoid closing your oldest accounts.',
    'cibil.securedLoans': 'Apply for Secured Loans',
    'cibil.securedLoansDesc': 'Secured loans are easier to obtain and help build a positive repayment record.',
    'cibil.whyZineegroup': 'Why You Should Check Your CIBIL Score with Zineegroup (and It\'s Free!)',
    'cibil.unlockDeals': 'Unlock Exclusive Loan & Credit Card Deals',
    'cibil.unlockDealsDesc': 'A strong credit score unlocks a world of financial opportunities. Access pre-approved loans and credit card deals from India\'s leading lenders and NBFCs, tailored to suit your unique financial profile. Enjoy benefits like minimal documentation, quick approvals, and even instant disbursal with these exclusive offers.',
    'cibil.effortlessCheck': 'Effortless Credit Score Check',
    'cibil.effortlessCheckDesc': 'Easily check your CIBIL score for free on our intuitive website or app. Get instant access to your credit score from multiple bureaus, anytime, anywhere, and stay informed about your financial health.',
    'cibil.simplifiedInsights': 'Simplified Credit Report Insights',
    'cibil.simplifiedInsightsDesc': 'Understanding credit reports can be tricky, but we\'ve got you covered. Our platform provides detailed explanations and simplified breakdowns of your credit report, helping you gain a clear understanding of your financial standing with ease.',
    'cibil.ctaTitle': 'Looking For Loan ?',
    'cibil.ctaText': 'Our Team Will Help For Providing Instant Loan In Low Interest Rate ! Apply Here.',
    'cibil.ctaNote': 'Our team of experienced professionals is dedicated to providing competitive interest rates, flexible repayment options, and a hassle-free application process.',
    'cibil.formNameLabel': 'Enter name as per Pan Card',
    'cibil.formNamePlaceholder': 'Name as per PAN Card',
    'cibil.formPanLabel': 'PAN Number',
    'cibil.formDobLabel': 'Date of Birth',
    'cibil.formMobileLabel': 'Mobile Number',
    'cibil.formEmailLabel': 'Email ID',
    'cibil.formCityLabel': 'City',
    'cibil.formCityPlaceholder': 'Enter city',
    'cibil.formPincodeLabel': 'Pincode',
    'cibil.formSuccess': 'Your CIBIL score enquiry has been submitted. We will contact you via email.',
    'cibil.formSubmitting': 'Submitting...',
    'cibil.contactEmailOnly': 'We will contact you only via email for your CIBIL score enquiry.',

    // EMI Calculator & Apply & Reviews & Compare
    'emi.pageTitle': 'EMI Calculator',
    'emi.pageDesc': 'Enter your loan amount, interest rate, and tenure to instantly see your monthly EMI, total interest, and total repayment.',
    'emi.calculateYour': 'Calculate Your',
    'emi.loanAmount': 'Loan Amount',
    'emi.rateOfInterest': 'Rate of Interest (p.a)',
    'emi.loanTenure': 'Loan Tenure',
    'emi.loanEmi': 'Loan EMI',
    'emi.totalInterestPayable': 'Total Interest Payable',
    'emi.totalPayment': 'Total Payment (Principal + Interest)',
    'emi.principalAmount': 'Principal Amount',
    'emi.totalInterest': 'Total Interest',
    'emi.yr': 'Yr',
    'emi.mo': 'Mo',
    'apply.title': 'Apply Now',
    'apply.intro': 'Get instant loan approval with competitive interest rates! Fill out the form below and our team will contact you within 24 hours.',
    'apply.quickApproval': 'Quick Approval',
    'apply.lowInterestRates': 'Low Interest Rates',
    'apply.minimalDoc': 'Minimal Documentation',
    'apply.flexibleRepayment': 'Flexible Repayment',
    'apply.callUsDirectly': 'Call Us Directly At',
    'apply.talkToExpert': 'Talk to an Expert',
    'apply.chatWithTeam': 'Chat With Our Team',
    'apply.personalInfo': 'Personal Information',
    'apply.fullName': 'Full Name',
    'apply.enterFullName': 'Enter your full name',
    'apply.emailAddress': 'Email Address',
    'apply.emailPlaceholder': 'your.email@example.com',
    'apply.phoneNumber': 'Phone Number',
    'apply.enterPhone': '10-digit mobile number',
    'apply.city': 'City',
    'apply.enterCity': 'Enter your city',
    'apply.pincode': 'Pincode',
    'apply.pincodePlaceholder': '6-digit pincode',
    'apply.tellUsAbout': 'Tell us about your loan requirements',
    'apply.messagePlaceholder': 'Please provide details about your loan purpose, preferred tenure, or any specific requirements...',
    'apply.submitting': 'Submitting...',
    'apply.applyNow': 'Apply Now',
    'apply.applyNowLine1': 'Apply',
    'apply.applyNowLine2': 'Now',
    'apply.successMessage': 'Success! Your loan application has been submitted. Our team will contact you within 24 hours.',
    'apply.errorMessage': 'There was an error submitting your application. Please try again.',
    'reviews.title': 'All Reviews',
    'reviews.intro': 'Read what our clients have to say about us',
    'reviews.allReviews': 'All Client Reviews',
    'reviews.happyClients': '12K + Happy Clients',
    'reviews.thankYou': 'Thank you! Your review has been submitted successfully.',
    'reviews.errorMessage': 'There was an error submitting your review. Please try again.',
    'reviews.writeReview': 'Write a Review',
    'reviews.shareExperience': 'Share your experience with us',
    'reviews.yourName': 'Your name',
    'reviews.yourEmail': 'Your email address',
    'reviews.yourReview': 'Write your review here...',
    'reviews.submitReview': 'Submit Review',
    'reviews.ratingOption': 'Rating',
    'reviews.starsExcellent': '5 Stars - Excellent',
    'reviews.starsVeryGood': '4 Stars - Very Good',
    'reviews.starsGood': '3 Stars - Good',
    'reviews.starsFair': '2 Stars - Fair',
    'reviews.starsPoor': '1 Star - Poor',
    'compare.title': 'Compare Personal Loans and Over Draft',
    'compare.subtitle': 'Select up to 3 banks to compare EMI, interest, fees, and features side by side. Values are based on your current calculator inputs.',
    'compare.remove': 'Remove',
    'compare.addBank': 'Add bank to compare',
    'compare.chooseBank': 'Choose a bank',
    'compare.addNbfc': 'Add Over Draft to compare',
    'compare.chooseNbfc': 'Choose Over Draft (Bajaj, Tata, etc.)',
    'compare.noMoreBanks': 'No more banks to add',
    'compare.comparison': 'Comparison',
    'compare.parameter': 'Parameter',
    'compare.monthlyEmi': 'Monthly EMI',
    'compare.totalInterestPayable': 'Total Interest Payable',
    'compare.totalPayment': 'Total Payment (Principal + Interest)',
    'compare.processingFee': 'Processing Fee',
    'compare.loanAmountRange': 'Loan Amount Range',
    'compare.tenureRange': 'Tenure Range',
    'compare.description': 'Description',
    'compare.keyFeatures': 'Key Features',
    'compare.apply': 'Apply',
    'compare.applyWith': 'Apply with',
    'compare.years': 'years',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.emi': 'ईएमआई कैलकुलेटर',
    'nav.apply': 'अभी आवेदन करें',
    'nav.cibil': 'सिबिल स्कोर',
    'nav.contact': 'विशेषज्ञ से बात करें',
    'nav.instantApproval': 'तत्काल ऋण',
    'nav.talkToExpert': 'विशेषज्ञ से बात करें',
    'nav.partner': 'भागीदार बनें',
    'nav.login': 'लॉगिन',

    // Partner Page
    'partner.title': 'भागीदार बनें',
    'partner.titlePrefix': '',
    'partner.titleHighlight': 'भागीदार',
    'partner.titleSuffix': ' बनें',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'हमारे ऋण प्रदाताओं के नेटवर्क में शामिल हों और अपना व्यवसाय बढ़ाएं।',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'आपका नाम',
    'partner.labelFullName': 'Full name',
    'partner.companyName': 'कंपनी का नाम',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.email': 'ईमेल पता',
    'partner.labelWorkEmail': 'Work email',
    'partner.phone': 'फ़ोन नंबर',
    'partner.labelPhone': 'Contact number',
    'partner.city': 'शहर',
    'partner.labelCity': 'City',
    'partner.message': 'संदेश',
    'partner.labelTellUsMore': 'How do you want to partner?',
    'partner.submit': 'अनुरोध सबमिट करें',
    'partner.submitting': 'सबमिट हो रहा है...',
    'partner.success': 'आवेदन सफलतापूर्वक सबमिट! हम जल्द संपर्क करेंगे।',
    'partner.error': 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
    'partner.benefitsHeading': 'Helloans के साथ पार्टनर बनने के लाभ',
    'partner.benefit1': 'लोन उत्पादों और ऋणदाताओं तक विस्तृत पहुंच',
    'partner.benefit2': 'आपकी टीम के लिए समर्पित सहायता और प्रशिक्षण',
    'partner.benefit3': 'प्रतिस्पर्धी कमीशन और समय पर भुगतान',
    'partner.benefit4': 'मार्केटिंग और लीड जनरेशन सहायता',
    'partner.benefit5': 'विश्वसनीय ब्रांड के साथ व्यवसाय बढ़ाएं',


    // Language switcher
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',

    // Hero
    'hero.title': 'आपके सर्वोत्तम जीवन के लिए सर्वोत्तम भविष्य प्रदान करना।',
    'hero.highlight': 'सर्वोत्तम',
    'hero.titleLine1': 'आपके सर्वोत्तम भविष्य के लिए',
    'hero.titleLine2': 'सर्वोत्तम जीवन प्रदान करना।',

    // Features
    'features.offer1Title': '₹1100 कैशबैक',
    'features.offer1Desc': '10 लाख से अधिक के ऋण पर प्रोसेसिंग फीस पर ₹1100 कैशबैक प्राप्त करें नियम और शर्तें लागू*',
    'features.offer1BackLine1': '10 लाख से अधिक ऋण राशि पर ₹1100 कैशबैक प्राप्त करें',
    'features.offer1BackLine2': 'प्रोसेसिंग फीस पर T&C*',
    'features.offer2Title': '₹3100 कैशबैक',
    'features.offer2Desc': '25 लाख से अधिक के ऋण पर प्रोसेसिंग फीस पर ₹3100 कैशबैक प्राप्त करें नियम और शर्तें लागू*',
    'features.offer2BackLine1': '25 लाख से अधिक ऋण राशि पर ₹3100 कैशबैक प्राप्त करें',
    'features.offer2BackLine2': 'प्रोसेसिंग फीस पर T&C*',
    'features.promiseTitle': 'हेलोअन्स प्रॉमिस',
    'features.promiseDesc': '(समय पर कैशबैक प्रदान करने का वादा) त्वरित संवितरण और कम ब्याज दर',
    'features.promiseBackLine1': 'नियम और शर्तें लागू',
    'features.promiseBackLine2': 'T&C*',

    // Carousel
    'carousel.instantLoan': 'तत्काल ऋण',
    'carousel.instantLoanDesc': 'अप्रत्याशित खर्चों के लिए आवश्यक धन प्राप्त करने का एक सुविधाजनक और तेज़ तरीका।',
    'carousel.overdraft': 'ओवरड्राफ्ट',
    'carousel.personalLoans': 'व्यक्तिगत ऋण',
    'carousel.personalLoansDesc': 'चाहे वह ऋण चुकौती के लिए हो या बड़े जीवन के लक्ष्य, व्यक्तिगत ऋण एक उत्कृष्ट वित्तीय साधन हो सकता है।',
    'carousel.businessLoans': 'व्यावसायिक ऋण',
    'carousel.businessLoansDesc': 'व्यावसायिक ऋण आपको अपने व्यवसाय और नेटवर्क का विस्तार करने में सक्षम बनाता है। यह आपके व्यवसाय में वित्तीय स्थिरता प्रदान करता है।',
    'carousel.professionalLoans': 'पेशेवर ऋण',
    'carousel.professionalLoansDesc': 'एक पेशेवर ऋण एक प्रकार का वित्तपोषण है जो पेशेवरों के लिए है, जैसे लेखाकार और वकील।',
    'carousel.secureLoans': 'सुरक्षित ऋण',
    'carousel.secureLoansDesc': 'सुरक्षित ऋण के साथ, आप कम ब्याज दरों के लिए पात्र हैं क्योंकि संपत्ति को सुरक्षा के रूप में गिरवी रखा जाता है।',
    'carousel.balanceTransfer': 'बैलेंस ट्रांसफर',
    'carousel.balanceTransferDesc': 'अपने मौजूदा ऋण को हमारे पास स्थानांतरित करें और बेहतर शर्तों और शर्तों के साथ ब्याज दरों पर बचत करें।',
    'carousel.homeLoans': 'होम लोन',
    'carousel.goldLoans': 'गोल्ड लोन',
    'carousel.educationLoans': 'शिक्षा ऋण',
    'carousel.insurance': 'बीमा',
    'carousel.creditCards': 'क्रेडिट कार्ड',
    'carousel.applyNow': 'अभी आवेदन करें',
    'carousel.viewAll': 'सभी देखें',

    // Loan Tiles Section
    'loanTiles.title': 'हमारे ऋण उत्पाद',

    // Trust Section
    'trust.title': 'विश्वास के साथ',
    'trust.titleHighlight': 'आत्मविश्वास',
    'trust.loansDisbursed': '₹ 15000 करोड़+',
    'trust.loansDisbursedDesc': 'हमारे उपयोगकर्ताओं को वितरित किए गए ऋणों की राशि',
    'trust.since2016': '2016 से',
    'trust.since2016Desc': '13 वर्षों का ग्राहक प्रेम और विश्वास',
    'trust.panIndia': 'पूरे भारत में',
    'trust.panIndiaDesc': 'आपकी सेवा, जहाँ भी आप हों',
    'trust.iso27001': 'ISO 27001',
    'trust.iso27001Desc': 'प्रमाणित डेटा सुरक्षा उत्कृष्टता',

    // Testimonials
    'testimonials.happyClients': '12K + खुश ग्राहक',
    'testimonials.title': 'ग्राहक अनुभव',
    'testimonials.readAll': 'सभी समीक्षा पढ़ें →',
    'testimonials.rating': 'रेटिंग',

    // Partners
    'partners.title': 'हमारे अधिकृत साझेदार',

    // Footer
    'footer.tagline': 'पैसा पाने का सबसे तेज़ तरीका',
    'footer.description': 'हमारी अनुभवी पेशेवरों की टीम प्रतिस्पर्धी ब्याज दरें, लचीले पुनर्भुगतान विकल्प और परेशानी मुक्त आवेदन प्रक्रिया प्रदान करने के लिए समर्पित है।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.getInTouch': 'संपर्क में रहें',
    'footer.socialMedia': 'सोशल मीडिया लिंक',
    'footer.copyright': '© कॉपीराइट 2026 | हेलोअन्स ज़िनी सर्विसेज प्राइवेट लिमिटेड (पूर्व में ज़िनी ग्रुप का हिस्सा)',

    // Talk to an Expert Page
    'expert.title': 'विशेषज्ञ से बात करें',
    'expert.subtitle': 'रियल टाइम में व्यक्तिगत लोन सलाह पाएं। बिना फॉर्म, बिना इंतजार—बस चैट करें।',
    'expert.liveHelp': 'लाइव सहायता उपलब्ध',
    'expert.cta': 'दाएं पैनल में चैट शुरू करें →',
    'expert.helpHeading': 'हम इसमें मदद कर सकते हैं',
    'expert.bullet1': 'लोन प्रकार और आपके लिए सर्वोत्तम विकल्प',
    'expert.bullet2': 'पात्रता और दस्तावेज़ सहायता',
    'expert.bullet3': 'आपके सवालों के तुरंत जवाब',
    'expert.emailLabel': 'ईमेल पसंद है?',
    'expert.email': 'info@zineegroup.com',
    'expert.phoneLabel': 'कॉल करें',
    'expert.chatLabel': 'चैट',

    // Contact
    'contact.getInTouch': 'संपर्क करें',
    'contact.talkToExpert': 'विशेषज्ञ से बात करें',
    'contact.chatbotIntro': 'लोन के बारे में सवाल हैं? हमारे विशेषज्ञ से चैट शुरू करें—बिना फॉर्म के।',
    'contact.chatbotDesc': 'चैटबॉट लोन प्रकार, पात्रता, दस्तावेज़ में मदद कर सकता है और आपको टीम से जोड़ सकता है।',
    'contact.startChat': 'चैट शुरू करें',
    'contact.socialMedia': 'सोशल मीडिया लिंक',
    'contact.name': 'नाम',
    'contact.email': 'ईमेल',
    'contact.phone': 'फोन नंबर',
    'contact.message': 'संदेश',
    'contact.submit': 'अभी जमा करें',
    'contact.submitting': 'जमा हो रहा है...',
    'contact.success': 'सफलता! आपका संदेश भेज दिया गया है। हम जल्द ही आपसे संपर्क करेंगे।',
    'contact.error': 'आपका संदेश भेजने में एक त्रुटि हुई। कृपया पुनः प्रयास करें।',

    // About Page
    'about.title': 'हमारे बारे में',
    'about.subtitle': 'हम लोगों और व्यवसायों के लिए अनुकूलित ऋण में विशेषज्ञता रखते हैं।',
    'about.learnMore': 'और जानें →',
    'about.gallery': 'गैलरी',
    'about.intro1': 'हम लोगों और व्यवसायों के लिए अनुकूलित ऋण में विशेषज्ञता रखते हैं। हम केवल एक और ऑनलाइन ऑफर तुलना साइट नहीं हैं। जबकि हम आपको सबसे व्यापक विकल्प देते हैं, हम अंतिम मील भी करते हैं और आपको ऋण भी दिलाते हैं। हम दृढ़ता से मानते हैं कि वित्तीय सेवाएं ई-कॉमर्स व्यवसाय की तरह नहीं हैं जहां उत्पाद मानकीकृत हैं और इसलिए सस्ता बेहतर है। हर उधारकर्ता की एक अद्वितीय वित्तीय स्थिति और आवश्यकता होती है।',
    'about.intro2': 'इसलिए, हमारे पास हमेशा एक समर्पित बिक्री प्रबंधक होता है जो आपको सर्वोत्तम बैंक चुनने की सलाह देता है, प्रारंभिक दस्तावेज़ीकरण करता है, आपकी ओर से बैंक प्रश्नों का उत्तर देता है, आपकी ओर से बातचीत करता है, ऋण दस्तावेज़ीकरण पूरा करता है और आपके खाते में वितरण सुनिश्चित करता है। हम ऐसा करने में सक्षम हैं क्योंकि हमारे पास 4000 शहरों में फैले 300 लोगों की मजबूत इन-हाउस टीम है। वरिष्ठ प्रबंधन में ऐसे लोग शामिल हैं जिन्होंने सिटीबैंक, स्टैंडर्ड चार्टर्ड बैंक, बजाज फिनसर्व आदि जैसे बैंकों/एनबीएफसी में नेतृत्व की भूमिकाएँ निभाई हैं।',
    'about.intro3': 'यह पूरी तरह से हमारे वफादार कर्मचारियों के प्रयासों के कारण है (पिछले 4 वर्षों में 5% से कम का कारोबार) कि हम वर्तमान में 4 वर्षों की कम कंपनी जीवनकाल के भीतर प्रति वर्ष 1,000 करोड़ से अधिक का वितरण कर रहे हैं। हमने ग्राहक के लिए प्रक्रिया को और भी सरल और सुव्यवस्थित बनाने के लिए एक रोमांचक यात्रा शुरू की है।',
    'about.loanTypes': 'असुरक्षित और सुरक्षित ऋण',
    'about.loanTypesSubtitle': 'हम सभी प्रकार के ऋण प्रदान कर रहे हैं।',
    'about.instantLoan': 'तत्काल ऋण',
    'about.personalLoans': 'व्यक्तिगत ऋण',
    'about.businessLoans': 'व्यावसायिक ऋण',
    'about.professionalLoans': 'पेशेवर ऋण',
    'about.secureLoans': 'सुरक्षित ऋण',
    'about.balanceTransfer': 'बैलेंस ट्रांसफर',
    'about.whyChoose': 'हमें क्यों चुनें',
    'about.whyChooseSubtitle': 'आपको हेलोअन्स क्यों चुनना चाहिए, इसके कई कारण हैं।',
    'about.whyChooseText': 'हमारी ऋण पेशेवरों की टीम के पास आपको प्रदान करने के लिए आवश्यक ज्ञान, कौशल, बाजार और इच्छा है।',
    'about.professionalService': 'पेशेवर सेवा',
    'about.ultraFastSupport': 'अल्ट्रा फास्ट सपोर्ट',
    'about.lowInterestLoan': 'कम ब्याज ऋण',
    'about.available24x7': '24x7 उपलब्ध',
    'about.ctaTitle': 'ऋण की तलाश है?',
    'about.ctaText': 'हमारी टीम कम ब्याज दर पर तत्काल ऋण प्रदान करने में मदद करेगी! यहाँ आवेदन करें।',
    'about.ctaDescription': 'हमारी अनुभवी पेशेवरों की टीम प्रतिस्पर्धी ब्याज दरें, लचीले पुनर्भुगतान विकल्प और परेशानी मुक्त आवेदन प्रक्रिया प्रदान करने के लिए समर्पित है।',

    // CIBIL Score Page
    'cibil.heroTitle': 'आज ही अपना मुफ्त क्रेडिट स्कोर जांचें!',
    'cibil.heroSubtitle': 'आज ही अपना मुफ्त क्रेडिट स्कोर जांचें!',
    'cibil.securityMessage': 'आपकी व्यक्तिगत जानकारी 100% हमारे साथ सुरक्षित है। हम आपका डेटा किसी तीसरे पक्ष के साथ साझा नहीं करते हैं।',
    'cibil.whatIsCreditScore': 'क्रेडिट स्कोर क्या है?',
    'cibil.whatIsCreditScoreText1': 'आपका क्रेडिट स्कोर आपकी वित्तीय विश्वसनीयता का एक आवश्यक संकेतक है, जो इस बात का माप है कि आप ऋणों का प्रबंधन और पुनर्भुगतान कितनी अच्छी तरह करते हैं। आमतौर पर 300 से 900 तक की तीन अंकों की संख्या के रूप में दर्शाया गया, यह आपकी साख को दर्शाता है और विभिन्न ऋण प्रकारों और क्रेडिट ब्यूरो से आपके क्रेडिट इतिहास और डेटा के आधार पर गणना की जाती है। यह स्कोर ऋणदाताओं और वित्तीय संस्थानों को समय पर उधार लिए गए धन का पुनर्भुगतान करने की आपकी संभावना का आकलन करने में मदद करता है।',
    'cibil.whatIsCreditScoreText2': 'एक उच्च क्रेडिट स्कोर, आमतौर पर 700 से अधिक को अच्छा माना जाता है, ऋण स्वीकृति की आपकी संभावनाओं को बेहतर बनाता है और बेहतर ब्याज दरें सुरक्षित करता है। भारत में, सबसे अधिक मान्यता प्राप्त क्रेडिट स्कोर ट्रांसयूनियन द्वारा प्रदान किया गया CIBIL स्कोर है। अन्य क्रेडिट ब्यूरो, जिनमें एक्सपेरियन, CRIF हाई मार्क और इक्विफैक्स शामिल हैं, आपकी क्रेडिट जानकारी को एकत्र करके और विश्लेषण करके आपका स्कोर उत्पन्न करने में भी योगदान देते हैं। पुनर्भुगतान इतिहास, ऋण के प्रकार, क्रेडिट उपयोग, क्रेडिट इतिहास की लंबाई और क्रेडिट आवेदनों की आवृत्ति जैसे कारक आपके स्कोर को प्रभावित करते हैं।',
    'cibil.creditScoreRange': 'क्रेडिट स्कोर की सीमा क्या है?',
    'cibil.creditScoreRangeText': 'क्रेडिट स्कोर, हालांकि ब्यूरो में थोड़ा भिन्न होते हैं, आमतौर पर 300 (सबसे कम) से 900 (सबसे अधिक) तक होते हैं। यदि आपके पास कोई क्रेडिट इतिहास नहीं है, तो आपको क्रेडिट कार्ड या ऋण का जिम्मेदारी से उपयोग करके इसे बनाने की आवश्यकता होगी। यहाँ क्रेडिट स्कोर रेंज और उनके निहितार्थों का अवलोकन है:',
    'cibil.badCredit': 'खराब क्रेडिट',
    'cibil.badCreditRange': '300-549',
    'cibil.badCreditDesc': 'चूक भुगतान, डिफॉल्ट, या उच्च क्रेडिट उपयोग को इंगित करता है। यह ऋण या क्रेडिट कार्ड प्राप्त करना मुश्किल बनाता है और अक्सर प्रतिकूल शर्तों की ओर जाता है।',
    'cibil.poorCredit': 'खराब क्रेडिट',
    'cibil.poorCreditRange': '550-649',
    'cibil.poorCreditDesc': 'कुछ पुनर्भुगतान समस्याओं का सुझाव देता है, जो ऋण स्वीकृतियों को सीमित कर सकता है या कम अनुकूल स्थितियों में परिणाम दे सकता है।',
    'cibil.fairCredit': 'उचित क्रेडिट',
    'cibil.fairCreditRange': '650-749',
    'cibil.fairCreditDesc': 'एक जिम्मेदार पुनर्भुगतान इतिहास को दर्शाता है, ऋण स्वीकृति की संभावनाओं में सुधार करता है लेकिन जरूरी नहीं कि सर्वोत्तम ब्याज दरों के साथ।',
    'cibil.goodCredit': 'अच्छा क्रेडिट',
    'cibil.goodCreditRange': '750-799',
    'cibil.goodCreditDesc': 'लगातार समय पर भुगतान और ध्वनि क्रेडिट प्रबंधन का प्रतिनिधित्व करता है, अनुकूल शर्तों के साथ ऋण स्वीकृति की संभावना को बढ़ाता है।',
    'cibil.excellentCredit': 'उत्कृष्ट क्रेडिट',
    'cibil.excellentCreditRange': '800-900',
    'cibil.excellentCreditDesc': 'असाधारण वित्तीय प्रबंधन का प्रदर्शन करता है, सबसे आकर्षक दरों और शर्तों के साथ ऋण और क्रेडिट कार्ड के लिए सर्वोत्तम अवसर प्रदान करता है।',
    'cibil.benefitsTitle': 'अच्छे क्रेडिट स्कोर के लाभ',
    'cibil.benefitsText1': 'आपका क्रेडिट स्कोर आपकी वित्तीय भलाई का एक महत्वपूर्ण माप है और आपके ऋण और क्रेडिट कार्ड विकल्पों को निर्धारित करने में महत्वपूर्ण भूमिका निभाता है। एक उच्च क्रेडिट स्कोर, आमतौर पर 700 से ऊपर, कई फायदे के साथ आता है। यह ऋण स्वीकृति की आपकी संभावनाओं को बढ़ाता है, आपको कम ब्याज दरों के लिए योग्य बनाता है, और आपको पैसे बचाने में मदद करता है।',
    'cibil.benefitsText2': 'एक मजबूत क्रेडिट स्कोर तेज़ प्रसंस्करण के साथ पूर्व-अनुमोदित ऋण और प्रीमियम पुरस्कार प्रदान करने वाले विशेष क्रेडिट कार्ड तक पहुंच भी प्रदान करता है। इसके अतिरिक्त, यह आपको उच्च क्रेडिट सीमा और लंबे ऋण पुनर्भुगतान शर्तों के लिए योग्य बना सकता है, अधिक लचीलापन प्रदान करता है और वित्तीय तनाव को कम करता है। एक अच्छे क्रेडिट स्कोर को बनाए रखना बेहतर क्रेडिट अवसरों के दरवाजे खोलता है और एक सुरक्षित वित्तीय भविष्य के लिए रास्ता तैयार करता है।',
    'cibil.buildCreditTitle': 'क्रेडिट बनाने का सबसे तेज़ तरीका क्या है?',
    'cibil.buildCreditText': 'एक मजबूत क्रेडिट स्कोर बनाना कई वित्तीय अवसरों को अनलॉक करता है, लेकिन शुरुआत से शुरू करना चुनौतीपूर्ण लग सकता है। अच्छी खबर यह है कि क्रेडिट स्थापित करना पूरी तरह से प्राप्त करने योग्य है! जिम्मेदार क्रेडिट उपयोग आपके स्कोर को बनाने का सबसे तेज़ तरीका है। अपने नाम पर एक क्रेडिट कार्ड प्राप्त करना एक बेहतरीन पहला कदम है। एक बार जब आपके पास एक हो, तो लगातार समय पर भुगतान करना एक सकारात्मक भुगतान इतिहास बनाने के लिए महत्वपूर्ण है, जो एक अच्छा क्रेडिट स्कोर बनाने में एक प्रमुख कारक है। नियमित रूप से अपनी क्रेडिट रिपोर्ट को त्रुटियों के लिए जांचना जो आपके स्कोर को नुकसान पहुंचा सकती है, समान रूप से महत्वपूर्ण है। इन चरणों का पालन करके, आप एक ठोस क्रेडिट नींव के लिए सही रास्ते पर होंगे।',
    'cibil.payOnTime': 'समय पर भुगतान करें',
    'cibil.payOnTimeDesc': 'एक अच्छा भुगतान इतिहास बनाए रखने के लिए हमेशा सभी ऋणों के लिए समय पर भुगतान को प्राथमिकता दें।',
    'cibil.limitInquiries': 'पूछताछ सीमित करें',
    'cibil.limitInquiriesDesc': 'अत्यधिक क्रेडिट आवेदनों से बचें, क्योंकि बहुत अधिक पूछताछ आपके स्कोर को कम कर सकती है।',
    'cibil.payDownBalances': 'बैलेंस कम करें',
    'cibil.payDownBalancesDesc': 'अपने क्रेडिट उपयोग अनुपात में सुधार करने के लिए क्रेडिट कार्ड बैलेंस को कम रखें।',
    'cibil.consolidateDebt': 'ऋण समेकित करें',
    'cibil.consolidateDebtDesc': 'क्रेडिट उपयोग को कम करने और पुनर्भुगतान को सरल बनाने के लिए एक समेकन ऋण का उपयोग करें।',
    'cibil.authorizedUser': 'अधिकृत उपयोगकर्ता बनें',
    'cibil.authorizedUserDesc': 'मजबूत भुगतान इतिहास वाले किसी के खाते से लिंक करना आपके स्कोर को बढ़ा सकता है (सावधानी से चुनें)।',
    'cibil.keepOldAccounts': 'पुराने खाते खुले रखें',
    'cibil.keepOldAccountsDesc': 'एक लंबा क्रेडिट इतिहास आपके स्कोर में सुधार करता है, इसलिए अपने सबसे पुराने खातों को बंद करने से बचें।',
    'cibil.securedLoans': 'सुरक्षित ऋण के लिए आवेदन करें',
    'cibil.securedLoansDesc': 'सुरक्षित ऋण प्राप्त करना आसान है और सकारात्मक पुनर्भुगतान रिकॉर्ड बनाने में मदद करते हैं।',
    'cibil.whyZineegroup': 'आपको ज़िनीग्रुप के साथ अपना CIBIL स्कोर क्यों जांचना चाहिए (और यह मुफ़्त है!)',
    'cibil.unlockDeals': 'विशेष ऋण और क्रेडिट कार्ड डील अनलॉक करें',
    'cibil.unlockDealsDesc': 'एक मजबूत क्रेडिट स्कोर वित्तीय अवसरों की दुनिया को अनलॉक करता है। भारत के प्रमुख ऋणदाताओं और एनबीएफसी से पूर्व-अनुमोदित ऋण और क्रेडिट कार्ड डील तक पहुंचें, जो आपकी अद्वितीय वित्तीय प्रोफ़ाइल के अनुरूप हैं। न्यूनतम दस्तावेज़ीकरण, त्वरित स्वीकृतियां, और इन विशेष ऑफ़र के साथ तत्काल वितरण जैसे लाभों का आनंद लें।',
    'cibil.effortlessCheck': 'सहज क्रेडिट स्कोर जांच',
    'cibil.effortlessCheckDesc': 'हमारी सहज वेबसाइट या ऐप पर मुफ्त में अपना CIBIL स्कोर आसानी से जांचें। कभी भी, कहीं भी कई ब्यूरो से अपने क्रेडिट स्कोर तक तत्काल पहुंच प्राप्त करें, और अपने वित्तीय स्वास्थ्य के बारे में सूचित रहें।',
    'cibil.simplifiedInsights': 'सरलीकृत क्रेडिट रिपोर्ट अंतर्दृष्टि',
    'cibil.simplifiedInsightsDesc': 'क्रेडिट रिपोर्ट को समझना मुश्किल हो सकता है, लेकिन हमने आपको कवर किया है। हमारा प्लेटफ़ॉर्म आपकी क्रेडिट रिपोर्ट के विस्तृत स्पष्टीकरण और सरलीकृत विश्लेषण प्रदान करता है, जिससे आप आसानी से अपनी वित्तीय स्थिति की स्पष्ट समझ प्राप्त कर सकते हैं।',
    'cibil.ctaTitle': 'ऋण की तलाश है?',
    'cibil.ctaText': 'हमारी टीम कम ब्याज दर पर तत्काल ऋण प्रदान करने में मदद करेगी! यहाँ आवेदन करें।',
    'cibil.ctaNote': 'हमारी अनुभवी पेशेवरों की टीम प्रतिस्पर्धी ब्याज दरें, लचीले पुनर्भुगतान विकल्प और परेशानी मुक्त आवेदन प्रक्रिया प्रदान करने के लिए समर्पित है।',
    'cibil.formNameLabel': 'पैन कार्ड के अनुसार नाम दर्ज करें',
    'cibil.formNamePlaceholder': 'पैन कार्ड के अनुसार नाम',
    'cibil.formPanLabel': 'पैन नंबर',
    'cibil.formDobLabel': 'जन्म तिथि',
    'cibil.formMobileLabel': 'मोबाइल नंबर',
    'cibil.formEmailLabel': 'ईमेल आईडी',
    'cibil.formCityLabel': 'शहर',
    'cibil.formCityPlaceholder': 'शहर दर्ज करें',
    'cibil.formPincodeLabel': 'पिनकोड',
    'cibil.formSuccess': 'आपकी CIBIL स्कोर जांच जमा कर दी गई है। हम आपसे ईमेल के माध्यम से संपर्क करेंगे।',
    'cibil.formSubmitting': 'जमा हो रहा है...',
    'cibil.contactEmailOnly': 'आपकी CIBIL स्कोर जांच के लिए हम आपसे केवल ईमेल के माध्यम से संपर्क करेंगे।',

    // EMI Calculator & Apply & Reviews & Compare (Hindi)
    'emi.pageTitle': 'ईएमआई कैलकुलेटर',
    'emi.pageDesc': 'अपना ऋण राशि, ब्याज दर और अवधि दर्ज करें और तुरंत मासिक ईएमआई, कुल ब्याज और कुल भुगतान देखें।',
    'emi.calculateYour': 'गणना करें',
    'emi.loanAmount': 'ऋण राशि',
    'emi.rateOfInterest': 'ब्याज दर (वार्षिक)',
    'emi.loanTenure': 'ऋण अवधि',
    'emi.loanEmi': 'ऋण ईएमआई',
    'emi.totalInterestPayable': 'कुल देय ब्याज',
    'emi.totalPayment': 'कुल भुगतान (मूलधन + ब्याज)',
    'emi.principalAmount': 'मूलधन राशि',
    'emi.totalInterest': 'कुल ब्याज',
    'emi.yr': 'वर्ष',
    'emi.mo': 'माह',
    'apply.title': 'अभी आवेदन करें',
    'apply.intro': 'प्रतिस्पर्धी ब्याज दरों के साथ तत्काल ऋण स्वीकृति पाएं! नीचे फॉर्म भरें और हमारी टीम 24 घंटे के भीतर संपर्क करेगी।',
    'apply.quickApproval': 'त्वरित स्वीकृति',
    'apply.lowInterestRates': 'कम ब्याज दरें',
    'apply.minimalDoc': 'न्यूनतम दस्तावेज़',
    'apply.flexibleRepayment': 'लचीला पुनर्भुगतान',
    'apply.callUsDirectly': 'सीधे कॉल करें',
    'apply.talkToExpert': 'विशेषज्ञ से बात करें',
    'apply.chatWithTeam': 'हमारी टीम से चैट करें',
    'apply.personalInfo': 'व्यक्तिगत जानकारी',
    'apply.fullName': 'पूरा नाम',
    'apply.enterFullName': 'अपना पूरा नाम दर्ज करें',
    'apply.emailAddress': 'ईमेल पता',
    'apply.emailPlaceholder': 'your.email@example.com',
    'apply.phoneNumber': 'फोन नंबर',
    'apply.enterPhone': '10 अंकों का मोबाइल नंबर',
    'apply.city': 'शहर',
    'apply.enterCity': 'अपना शहर दर्ज करें',
    'apply.pincode': 'पिनकोड',
    'apply.pincodePlaceholder': '6 अंकों का पिनकोड',
    'apply.tellUsAbout': 'अपनी ऋण आवश्यकताओं के बारे में बताएं',
    'apply.messagePlaceholder': 'कृपया अपने ऋण उद्देश्य, पसंदीदा अवधि या विशेष आवश्यकताओं के बारे में विवरण दें...',
    'apply.submitting': 'जमा हो रहा है...',
    'apply.applyNow': 'अभी आवेदन करें',
    'apply.applyNowLine1': 'आवेदन',
    'apply.applyNowLine2': 'अभी',
    'apply.successMessage': 'सफलता! आपका ऋण आवेदन जमा हो गया। हमारी टीम 24 घंटे के भीतर संपर्क करेगी।',
    'apply.errorMessage': 'आपका आवेदन जमा करने में त्रुटि हुई। कृपया पुनः प्रयास करें।',
    'reviews.title': 'सभी समीक्षाएं',
    'reviews.intro': 'पढ़ें कि हमारे ग्राहक हमारे बारे में क्या कहते हैं',
    'reviews.allReviews': 'सभी ग्राहक समीक्षाएं',
    'reviews.happyClients': '12K + खुश ग्राहक',
    'reviews.thankYou': 'धन्यवाद! आपकी समीक्षा सफलतापूर्वक जमा हो गई।',
    'reviews.errorMessage': 'आपकी समीक्षा जमा करने में त्रुटि हुई। कृपया पुनः प्रयास करें।',
    'reviews.writeReview': 'समीक्षा लिखें',
    'reviews.shareExperience': 'हमारे साथ अपना अनुभव साझा करें',
    'reviews.yourName': 'आपका नाम',
    'reviews.yourEmail': 'आपका ईमेल पता',
    'reviews.yourReview': 'अपनी समीक्षा यहाँ लिखें...',
    'reviews.submitReview': 'समीक्षा जमा करें',
    'reviews.ratingOption': 'रेटिंग',
    'reviews.starsExcellent': '5 स्टार - उत्कृष्ट',
    'reviews.starsVeryGood': '4 स्टार - बहुत अच्छा',
    'reviews.starsGood': '3 स्टार - अच्छा',
    'reviews.starsFair': '2 स्टार - ठीक',
    'reviews.starsPoor': '1 स्टार - कम',
    'compare.title': 'तुलना करें व्यक्तिगत ऋण और ओवर ड्राफ्ट',
    'compare.subtitle': 'ईएमआई, ब्याज, शुल्क और सुविधाओं की तुलना करने के लिए 3 बैंक चुनें। मान आपके कैलकुलेटर इनपुट पर आधारित हैं।',
    'compare.remove': 'हटाएं',
    'compare.addBank': 'तुलना के लिए बैंक जोड़ें',
    'compare.chooseBank': 'बैंक चुनें',
    'compare.addNbfc': 'ओवर ड्राफ्ट जोड़ें तुलना के लिए',
    'compare.chooseNbfc': 'ओवर ड्राफ्ट चुनें (बजाज, टाटा, आदि)',
    'compare.noMoreBanks': 'जोड़ने के लिए और बैंक नहीं',
    'compare.comparison': 'तुलना',
    'compare.parameter': 'पैरामीटर',
    'compare.monthlyEmi': 'मासिक ईएमआई',
    'compare.totalInterestPayable': 'कुल देय ब्याज',
    'compare.totalPayment': 'कुल भुगतान (मूलधन + ब्याज)',
    'compare.processingFee': 'प्रोसेसिंग शुल्क',
    'compare.loanAmountRange': 'ऋण राशि सीमा',
    'compare.tenureRange': 'अवधि सीमा',
    'compare.description': 'विवरण',
    'compare.keyFeatures': 'मुख्य विशेषताएं',
    'compare.apply': 'आवेदन',
    'compare.applyWith': 'के साथ आवेदन करें',
    'compare.years': 'वर्ष',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.emi': 'EMI கணிப்பான்',
    'nav.apply': 'இப்போது விண்ணப்பிக்கவும்',
    'nav.cibil': 'சிபில் மதிப்பெண்',
    'nav.contact': 'நிபுணருடன் பேசுங்கள்',
    'nav.partner': 'பங்குதாரராகுங்கள்',
    'nav.login': 'உள்நுழைய',
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',
    'hero.title': 'உங்கள் சிறந்த வாழ்க்கைக்கு சிறந்த எதிர்காலத்தை வழங்குதல்.',
    'hero.highlight': 'சிறந்த',
    'hero.titleLine1': 'சிறந்த எதிர்காலத்தை',
    'hero.titleLine2': 'உங்கள் சிறந்த வாழ்க்கைக்கு வழங்குகிறோம்.',
    'features.offer1Title': '₹1100 கேஷ்பேக்',
    'features.offer1Desc': '10 லட்சத்திற்கு மேலான கடன் தொகையில் செயலாக்கக் கட்டணத்தில் ₹1100 கேஷ்பேக் பெறுங்கள் T&C*',
    'features.offer1BackLine1': '10 லட்சத்திற்கு மேலான கடன் தொகையில் ₹1100 கேஷ்பேக் பெறுங்கள்',
    'features.offer1BackLine2': 'செயலாக்கக் கட்டணத்தில் T&C*',
    'features.offer2Title': '₹3100 கேஷ்பேக்',
    'features.offer2Desc': '25 லட்சத்திற்கு மேலான கடன் தொகையில் செயலாக்கக் கட்டணத்தில் ₹3100 கேஷ்பேக் பெறுங்கள் T&C*',
    'features.offer2BackLine1': '25 லட்சத்திற்கு மேலான கடன் தொகையில் ₹3100 கேஷ்பேக் பெறுங்கள்',
    'features.offer2BackLine2': 'செயலாக்கக் கட்டணத்தில் T&C*',
    'features.promiseTitle': 'ஹலோன்ஸ் வாக்குறுதி',
    'features.promiseDesc': '(கேஷ்பேக்கை சரியான நேரத்தில் வழங்க) விரைவான விநியோகம் மற்றும் குறைந்த வட்டி',
    'features.promiseBackLine1': 'விதிமுறைகள் மற்றும் நிபந்தனைகள் பொருந்தும்',
    'features.promiseBackLine2': 'T&C*',
    'carousel.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'carousel.viewAll': 'அனைத்தையும் பார்',
    'loanTiles.title': 'எங்கள் கடன் தயாரிப்புகள்',
    'trust.title': 'நம்பிக்கையுடன்',
    'trust.titleHighlight': 'விடாமுயற்சி',
    'trust.loansDisbursed': '₹ 15000 கோடி+',
    'trust.loansDisbursedDesc': 'பயனர்களுக்கு வழங்கப்பட்ட கடன்களின் மதிப்பு',
    'trust.since2016': '2016 முதல்',
    'trust.panIndia': 'இந்தியா முழுவதும்',
    'trust.iso27001': 'ISO 27001',
    'testimonials.happyClients': '12K + மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    'testimonials.title': 'வாடிக்கையாளர் அனுபவங்கள்',
    'testimonials.readAll': 'அனைத்து மதிப்புரைகளையும் படிக்கவும் →',
    'testimonials.rating': 'மதிப்பீடு',
    'partners.title': 'எங்கள் அங்கீகரிக்கப்பட்ட பங்குதாரர்கள்',
    'footer.tagline': 'பணம் பெறுவதற்கான வேகமான வழி',
    'footer.quickLinks': 'விரைவு இணைப்புகள்',
    'footer.getInTouch': 'தொடர்பு கொள்ளுங்கள்',
    'footer.socialMedia': 'சமூக ஊடக இணைப்புகள்',
    'footer.copyright': '© பதிப்புரிமை 2026 | HELLOANS ZINEE SERVICES PVT LTD',
    'contact.getInTouch': 'தொடர்பு கொள்ளுங்கள்',
    'contact.talkToExpert': 'நிபுணருடன் பேசுங்கள்',
    'contact.chatbotIntro': 'கடன் குறித்த கேள்விகள் உள்ளனவா? எங்கள் நிபுணருடன் சாட் தொடங்குங்கள்—படிவம் தேவையில்லை.',
    'contact.chatbotDesc': 'கடன் வகைகள், தகுதி, ஆவணங்கள் உதவும்; அணியுடன் இணைக்கலாம்.',
    'contact.startChat': 'சாட் தொடங்கு',
    'contact.name': 'பெயர்',
    'contact.email': 'மின்னஞ்சல்',
    'contact.phone': 'தொலைபேசி',
    'contact.message': 'செய்தி',
    'contact.submit': 'அனுப்பவும்',
    'contact.submitting': 'அனுப்பப்படுகிறது...',
    'partner.title': 'பங்குதாரராகுங்கள்',
    'partner.titlePrefix': '',
    'partner.titleHighlight': 'பங்குதாரராகுங்கள்',
    'partner.titleSuffix': '',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'கடன் வழங்குநர்கள் வலையமைப்பில் சேர்ந்து உங்கள் வணிகத்தை வளர்த்தெடுங்கள்.',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'உங்கள் பெயர்',
    'partner.labelFullName': 'Full name',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.labelWorkEmail': 'Work email',
    'partner.labelPhone': 'Contact number',
    'partner.labelCity': 'City',
    'partner.labelTellUsMore': 'How do you want to partner?',
    'partner.companyName': 'நிறுவனப் பெயர்',
    'partner.email': 'மின்னஞ்சல்',
    'partner.phone': 'தொலைபேசி',
    'partner.city': 'நகரம்',
    'partner.message': 'செய்தி',
    'partner.submit': 'கோரிக்கை சமர்ப்பிக்கவும்',
    'partner.submitting': 'சமர்ப்பிக்கப்படுகிறது...',
    'partner.success': 'விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! விரைவில் தொடர்பு கொள்வோம்.',
    'partner.error': 'பொருந்தாதது. மீண்டும் முயற்சிக்கவும்.',
    'partner.benefitsHeading': 'Helloans பங்குதாரராக இணைவதன் நன்மைகள்',
    'partner.benefit1': 'கடன் தயாரிப்புகள் மற்றும் கடன் வழங்குநர்களுக்கு அணுகல்',
    'partner.benefit2': 'உங்கள் குழுவிற்கான அர்ப்பணிப்பு ஆதரவு மற்றும் பயிற்சி',
    'partner.benefit3': 'போட்டி கமிஷன் மற்றும் சரியான நேரத்தில் செலுத்துதல்',
    'partner.benefit4': 'சந்தைப்படுத்தல் மற்றும் லீட் உருவாக்கம் ஆதரவு',
    'partner.benefit5': 'நம்பகமான பிராண்டுடன் உங்கள் வணிகத்தை வளர்த்துக் கொள்ளுங்கள்',
    'about.title': 'எங்களைப் பற்றி',
    'about.subtitle': 'நபர்கள் மற்றும் வணிகங்களுக்கான தனிப்பயன் கடனில் நாங்கள் நிபுணத்துவம் பெற்றுள்ளோம்.',
    'about.learnMore': 'மேலும் அறிக →',
    'about.gallery': 'கேலரி',
    'emi.pageTitle': 'EMI கணிப்பான்',
    'emi.pageDesc': 'கடன் தொகை, வட்டி விகிதம் மற்றும் காலத்தை உள்ளிடவும்; மாதாந்திர EMI, மொத்த வட்டி மற்றும் மொத்த திருப்பிச் செலுத்துதலை உடனடியாகப் பாருங்கள்.',
    'emi.calculateYour': 'கணக்கிடுங்கள்',
    'emi.loanAmount': 'கடன் தொகை',
    'emi.rateOfInterest': 'வட்டி விகிதம் (வருடாந்திர)',
    'emi.loanTenure': 'கடன் காலம்',
    'emi.loanEmi': 'கடன் EMI',
    'emi.totalInterestPayable': 'மொத்த வட்டி செலுத்துதல்',
    'emi.totalPayment': 'மொத்த திருப்பிச் செலுத்துதல் (அசல் + வட்டி)',
    'emi.principalAmount': 'அசல் தொகை',
    'emi.totalInterest': 'மொத்த வட்டி',
    'emi.yr': 'ஆண்டு',
    'emi.mo': 'மாதம்',
    'apply.title': 'இப்போது விண்ணப்பிக்கவும்',
    'apply.intro': 'போட்டி வட்டி விகிதங்களுடன் உடனடி கடன் அங்கீகாரம் பெறுங்கள்! கீழே உள்ள படிவத்தை பூர்த்தி செய்யுங்கள், எங்கள் குழு 24 மணி நேரத்திற்குள் தொடர்பு கொள்ளும்.',
    'apply.quickApproval': 'விரைவு அங்கீகாரம்',
    'apply.lowInterestRates': 'குறைந்த வட்டி விகிதங்கள்',
    'apply.minimalDoc': 'குறைந்த ஆவணங்கள்',
    'apply.flexibleRepayment': 'நெகிழ்வான திருப்பிச் செலுத்துதல்',
    'apply.callUsDirectly': 'நேரடியாக அழைக்கவும்',
    'apply.talkToExpert': 'நிபுணருடன் பேசுங்கள்',
    'apply.chatWithTeam': 'எங்கள் குழுவுடன் அரட்டை',
    'apply.personalInfo': 'தனிப்பட்ட தகவல்',
    'apply.fullName': 'முழு பெயர்',
    'apply.enterFullName': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'apply.emailAddress': 'மின்னஞ்சல் முகவரி',
    'apply.phoneNumber': 'தொலைபேசி எண்',
    'apply.enterPhone': '10 இலக்க மொபைல் எண்',
    'apply.city': 'நகரம்',
    'apply.enterCity': 'உங்கள் நகரத்தை உள்ளிடவும்',
    'apply.pincode': 'அஞ்சல் குறியீடு',
    'apply.pincodePlaceholder': '6 இலக்க அஞ்சல் குறியீடு',
    'apply.tellUsAbout': 'உங்கள் கடன் தேவைகளைப் பற்றி சொல்லுங்கள்',
    'apply.submitting': 'சமர்ப்பிக்கப்படுகிறது...',
    'apply.applyNow': 'இப்போது விண்ணப்பிக்கவும்',
    'apply.applyNowLine1': 'விண்ணப்பி',
    'apply.applyNowLine2': 'இப்போது',
    'apply.successMessage': 'வெற்றி! உங்கள் கடன் விண்ணப்பம் சமர்ப்பிக்கப்பட்டது. எங்கள் குழு 24 மணி நேரத்திற்குள் தொடர்பு கொள்ளும்.',
    'apply.errorMessage': 'விண்ணப்பம் சமர்ப்பிப்பதில் பிழை. மீண்டும் முயற்சிக்கவும்.',
    'reviews.title': 'அனைத்து மதிப்புரைகள்',
    'reviews.intro': 'எங்கள் வாடிக்கையாளர்கள் எங்களைப் பற்றி என்ன சொல்கிறார்கள் என்று படிக்கவும்',
    'reviews.allReviews': 'அனைத்து வாடிக்கையாளர் மதிப்புரைகள்',
    'reviews.happyClients': '12K + மகிழ்ச்சியான வாடிக்கையாளர்கள்',
    'reviews.thankYou': 'நன்றி! உங்கள் மதிப்புரை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.',
    'reviews.errorMessage': 'மதிப்புரை சமர்ப்பிப்பதில் பிழை. மீண்டும் முயற்சிக்கவும்.',
    'reviews.writeReview': 'மதிப்புரை எழுதுங்கள்',
    'reviews.shareExperience': 'எங்களுடன் உங்கள் அனுபவத்தை பகிர்ந்து கொள்ளுங்கள்',
    'reviews.yourName': 'உங்கள் பெயர்',
    'reviews.yourEmail': 'உங்கள் மின்னஞ்சல்',
    'reviews.yourReview': 'உங்கள் மதிப்புரையை இங்கே எழுதுங்கள்...',
    'reviews.submitReview': 'மதிப்புரையை சமர்ப்பிக்கவும்',
    'reviews.ratingOption': 'மதிப்பீடு',
    'compare.title': 'ஒப்பிடுங்கள் தனிப்பட்ட கடன்கள் மற்றும் ஓவர் டிராஃப்ட்',
    'compare.subtitle': 'EMI, வட்டி, கட்டணங்கள் மற்றும் அம்சங்களை பக்கத்தில் ஒப்பிட 3 வங்கிகளைத் தேர்ந்தெடுக்கவும்.',
    'compare.remove': 'அகற்று',
    'compare.addBank': 'ஒப்பிட வங்கி சேர்',
    'compare.chooseBank': 'வங்கியைத் தேர்ந்தெடுக்கவும்',
    'compare.addNbfc': 'ஒப்பிட ஓவர் டிராஃப்ட் சேர்',
    'compare.chooseNbfc': 'ஓவர் டிராஃப்ட் தேர்ந்தெடு (பஜாஜ், டாடா, முதலியன)',
    'compare.noMoreBanks': 'சேர்க்க மேலும் வங்கிகள் இல்லை',
    'compare.comparison': 'ஒப்பீடு',
    'compare.parameter': 'அளவுரு',
    'compare.monthlyEmi': 'மாதாந்திர EMI',
    'compare.totalInterestPayable': 'மொத்த வட்டி செலுத்துதல்',
    'compare.totalPayment': 'மொத்த திருப்பிச் செலுத்துதல்',
    'compare.processingFee': 'செயலாக்க கட்டணம்',
    'compare.loanAmountRange': 'கடன் தொகை வரம்பு',
    'compare.tenureRange': 'கால வரம்பு',
    'compare.description': 'விளக்கம்',
    'compare.keyFeatures': 'முக்கிய அம்சங்கள்',
    'compare.apply': 'விண்ணப்பிக்கவும்',
    'compare.applyWith': 'விண்ணப்பிக்கவும்',
    'compare.years': 'ஆண்டுகள்',
    'cibil.heroTitle': 'இன்று உங்கள் இலவச கிரெடிட் மதிப்பெண்ணை சரிபார்க்கவும்!',
    'cibil.securityMessage': 'உங்கள் தனிப்பட்ட தகவல் 100% பாதுகாக்கப்பட்டுள்ளது.',
    'cibil.formNameLabel': 'பான் அட்டையின் படி பெயர்',
    'cibil.formPanLabel': 'பான் எண்',
    'cibil.formDobLabel': 'பிறந்த தேதி',
    'cibil.formMobileLabel': 'மொபைல் எண்',
    'cibil.formEmailLabel': 'மின்னஞ்சல்',
    'cibil.formCityLabel': 'நகரம்',
    'cibil.formPincodeLabel': 'அஞ்சல் குறியீடு',
    'cibil.formSubmitting': 'சமர்ப்பிக்கப்படுகிறது...',
  } as Record<string, string>,
  te: {
    'nav.home': 'హోమ్',
    'nav.about': 'మా గురించి',
    'nav.emi': 'EMI కాల్క్యులేటర్',
    'nav.apply': 'ఇప్పుడు అప్లై చేయండి',
    'nav.cibil': 'సిబిల్ స్కోర్',
    'nav.contact': 'నిపుణుడితో మాట్లాడండి',
    'nav.partner': 'పార్టనర్ అవ్వండి',
    'nav.login': 'లాగిన్',
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',
    'hero.title': 'మీ ఉత్తమ జీవనానికి ఉత్తమ భవిష్యత్తును అందించడం.',
    'hero.highlight': 'ఉత్తమ',
    'hero.titleLine1': 'ఉత్తమ భవిష్యత్తును',
    'hero.titleLine2': 'మీ ఉత్తమ జీవనానికి అందించడం.',
    'features.offer1Title': '₹1100 క్యాష్‌బ్యాక్',
    'features.offer1Desc': '10 లక్షల కంటే ఎక్కువ లోన్ మొత్తానికి ప్రాసెసింగ్ ఫీజుపై ₹1100 క్యాష్‌బ్యాక్ పొందండి T&C*',
    'features.offer1BackLine1': '10 లక్షల కంటే ఎక్కువ లోన్ మొత్తానికి ₹1100 క్యాష్‌బ్యాక్ పొందండి',
    'features.offer1BackLine2': 'ప్రాసెసింగ్ ఫీజుపై T&C*',
    'features.offer2Title': '₹3100 క్యాష్‌బ్యాక్',
    'features.offer2Desc': '25 లక్షల కంటే ఎక్కువ లోన్ మొత్తానికి ప్రాసెసింగ్ ఫీజుపై ₹3100 క్యాష్‌బ్యాక్ పొందండి T&C*',
    'features.offer2BackLine1': '25 లక్షల కంటే ఎక్కువ లోన్ మొత్తానికి ₹3100 క్యాష్‌బ్యాక్ పొందండి',
    'features.offer2BackLine2': 'ప్రాసెసింగ్ ఫీజుపై T&C*',
    'features.promiseTitle': 'హలోన్స్ ప్రామిస్',
    'features.promiseDesc': '(సమయానికి క్యాష్‌బ్యాక్ అందించడానికి) వేగవంతమైన పంపిణీ & తక్కువ వడ్డీ',
    'features.promiseBackLine1': 'నిబంధనలు మరియు షరతులు వర్తిస్తాయి',
    'features.promiseBackLine2': 'T&C*',
    'carousel.applyNow': 'ఇప్పుడు అప్లై చేయండి',
    'loanTiles.title': 'మా లోన్ ఉత్పత్తులు',
    'trust.title': 'విశ్వాసంతో',
    'trust.titleHighlight': 'ఆత్మవిశ్వాసం',
    'trust.loansDisbursed': '₹ 15000 కోట్ల+',
    'trust.loansDisbursedDesc': 'వినియోగదారులకు వితరణ చేసిన రుణాల విలువ',
    'trust.since2016': '2016 నుండి',
    'trust.panIndia': 'పాన్ ఇండియా',
    'testimonials.happyClients': '12K + సంతోషిత క్లయింట్లు',
    'testimonials.title': 'క్లయింట్ అనుభవాలు',
    'testimonials.readAll': 'అన్ని సమీక్షలు చదవండి →',
    'testimonials.rating': 'రేటింగ్',
    'partners.title': 'మా అధీకృత భాగస్వాములు',
    'footer.tagline': 'డబ్బు పొందడానికి వేగమైన మార్గం',
    'footer.quickLinks': 'త్వరిత లింకులు',
    'footer.getInTouch': 'సంప్రదించండి',
    'footer.socialMedia': 'సోషల్ మీడియా లింకులు',
    'footer.copyright': '© కాపీరైట్ 2026 | HELLOANS ZINEE SERVICES PVT LTD',
    'contact.getInTouch': 'సంప్రదించండి',
    'contact.talkToExpert': 'నిపుణులతో మాట్లాడండి',
    'contact.chatbotIntro': 'లోన్ల గురించి ప్రశ్నలు ఉన్నాయా? ఫారమ్ లేకుండా మా నిపుణులతో చాట్ ప్రారంభించండి.',
    'contact.chatbotDesc': 'లోన్ రకాలు, అర్హత, డాక్యుమెంట్స్ సహాయం మరియు టీమ్‌కు కనెక్ట్ అవ్వండి.',
    'contact.startChat': 'చాట్ ప్రారంభించండి',
    'contact.name': 'పేరు',
    'contact.email': 'ఇమెయిల్',
    'contact.phone': 'ఫోన్',
    'contact.message': 'సందేశం',
    'contact.submit': 'సమర్పించండి',
    'contact.submitting': 'సమర్పిస్తోంది...',
    'partner.title': 'పార్టనర్ అవ్వండి',
    'partner.titlePrefix': '',
    'partner.titleHighlight': 'పార్టనర్',
    'partner.titleSuffix': ' అవ్వండి',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'రుణ ఇచ్చేవారి నెట్‌వర్క్‌లో చేరండి మరియు మీ వ్యాపారాన్ని అభివృద్ధి చేయండి.',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'మీ పేరు',
    'partner.labelFullName': 'Full name',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.labelWorkEmail': 'Work email',
    'partner.labelPhone': 'Contact number',
    'partner.labelCity': 'City',
    'partner.labelTellUsMore': 'How do you want to partner?',
    'partner.companyName': 'కంపెనీ పేరు',
    'partner.email': 'ఇమెయిల్',
    'partner.phone': 'ఫోన్ నంబర్',
    'partner.city': 'నగరం',
    'partner.message': 'సందేశం',
    'partner.submit': 'అభ్యర్థన సమర్పించండి',
    'partner.submitting': 'సమర్పిస్తోంది...',
    'partner.success': 'అప్లికేషన్ విజయవంతంగా సమర్పించబడింది! త్వరలో సంప్రదిస్తాము.',
    'partner.error': 'ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.',
    'partner.benefitsHeading': 'Helloans పార్టనర్ అయ్యే ప్రయోజనాలు',
    'partner.benefit1': 'లోన్ ఉత్పత్తులు మరియు రుణదాతలకు విస్తృత ప్రవేశం',
    'partner.benefit2': 'మీ టీమ్ కోసం అంకితమైన మద్దతు మరియు శిక్షణ',
    'partner.benefit3': 'పోటీ కమీషన్ మరియు సకాలంలో చెల్లింపులు',
    'partner.benefit4': 'మార్కెటింగ్ మరియు లీడ్ జనరేషన్ మద్దతు',
    'partner.benefit5': 'నమ్మకమైన బ్రాండ్ తో మీ వ్యాపారాన్ని అభివృద్ధి చేయండి',
    'about.title': 'మా గురించి',
    'about.subtitle': 'వ్యక్తులు మరియు వ్యాపారాలకు అనుకూల రుణంలో మేము నిపుణత కలిగి ఉన్నాము.',
    'about.learnMore': 'మరింత తెలుసుకోండి →',
    'about.gallery': 'గ్యాలరీ',
    'emi.pageTitle': 'EMI కాల్క్యులేటర్',
    'emi.pageDesc': 'రుణ మొత్తం, వడ్డీ రేటు మరియు కాలాన్ని నమోదు చేయండి; నెలవారీ EMI, మొత్తం వడ్డీ మరియు మొత్తం చెల్లింపును తక్షణమే చూడండి.',
    'emi.calculateYour': 'లెక్కించండి',
    'emi.loanAmount': 'రుణ మొత్తం',
    'emi.rateOfInterest': 'వడ్డీ రేటు (సంవత్సరానికి)',
    'emi.loanTenure': 'రుణ కాలం',
    'emi.loanEmi': 'రుణ EMI',
    'emi.totalInterestPayable': 'మొత్తం వడ్డీ చెల్లించాలి',
    'emi.totalPayment': 'మొత్తం చెల్లింపు (ప్రధాన + వడ్డీ)',
    'emi.principalAmount': 'ప్రధాన మొత్తం',
    'emi.totalInterest': 'మొత్తం వడ్డీ',
    'emi.yr': 'సం',
    'emi.mo': 'నెల',
    'apply.title': 'ఇప్పుడు అప్లై చేయండి',
    'apply.intro': 'పోటీ వడ్డీ రేట్లతో తక్షణ రుణ ఆమోదం పొందండి! క్రింద ఫారమ్ పూరించండి, మా బృందం 24 గంటలలో సంప్రదిస్తుంది.',
    'apply.quickApproval': 'త్వరిత ఆమోదం',
    'apply.lowInterestRates': 'తక్కువ వడ్డీ రేట్లు',
    'apply.minimalDoc': 'కనిష్ట డాక్యుమెంటేషన్',
    'apply.flexibleRepayment': 'అనువైన తిరిగి చెల్లింపు',
    'apply.callUsDirectly': 'నేరుగా కాల్ చేయండి',
    'apply.talkToExpert': 'నిపుణుడితో మాట్లాడండి',
    'apply.chatWithTeam': 'మా బృందంతో చాట్ చేయండి',
    'apply.personalInfo': 'వ్యక్తిగత సమాచారం',
    'apply.fullName': 'పూర్తి పేరు',
    'apply.enterFullName': 'మీ పూర్తి పేరు నమోదు చేయండి',
    'apply.emailAddress': 'ఇమెయిల్ చిరునామా',
    'apply.phoneNumber': 'ఫోన్ నంబర్',
    'apply.enterPhone': '10 అంకెల మొబైల్ నంబర్',
    'apply.city': 'నగరం',
    'apply.enterCity': 'మీ నగరం నమోదు చేయండి',
    'apply.pincode': 'పిన్ కోడ్',
    'apply.pincodePlaceholder': '6 అంకెల పిన్ కోడ్',
    'apply.tellUsAbout': 'మీ రుణ అవసరాల గురించి చెప్పండి',
    'apply.submitting': 'సమర్పిస్తోంది...',
    'apply.applyNow': 'ఇప్పుడు అప్లై చేయండి',
    'apply.applyNowLine1': 'అప్లై',
    'apply.applyNowLine2': 'ఇప్పుడు',
    'apply.successMessage': 'విజయం! మీ రుణ అప్లికేషన్ సమర్పించబడింది. మా బృందం 24 గంటలలో సంప్రదిస్తుంది.',
    'apply.errorMessage': 'అప్లికేషన్ సమర్పించడంలో లోపం. మళ్లీ ప్రయత్నించండి.',
    'reviews.title': 'అన్ని సమీక్షలు',
    'reviews.intro': 'మా క్లయింట్లు మా గురించి ఏమి చెబుతారో చదవండి',
    'reviews.allReviews': 'అన్ని క్లయింట్ సమీక్షలు',
    'reviews.happyClients': '12K + సంతోషిత క్లయింట్లు',
    'reviews.thankYou': 'ధన్యవాదాలు! మీ సమీక్ష విజయవంతంగా సమర్పించబడింది.',
    'reviews.errorMessage': 'సమీక్ష సమర్పించడంలో లోపం. మళ్లీ ప్రయత్నించండి.',
    'reviews.writeReview': 'సమీక్ష రాయండి',
    'reviews.shareExperience': 'మాతో మీ అనుభవాన్ని భాగస్వామ్యం చేయండి',
    'reviews.yourName': 'మీ పేరు',
    'reviews.yourEmail': 'మీ ఇమెయిల్',
    'reviews.yourReview': 'మీ సమీక్ష ఇక్కడ రాయండి...',
    'reviews.submitReview': 'సమీక్ష సమర్పించండి',
    'reviews.ratingOption': 'రేటింగ్',
    'compare.title': 'సరిపోల్చండి వ్యక్తిగత రుణాలు మరియు ఓవర్ డ్రాఫ్ట్',
    'compare.subtitle': 'EMI, వడ్డీ, ఫీజులు మరియు ఫీచర్లను పక్కపక్కనే సరిపోల్చడానికి 3 బ్యాంకులను ఎంచుకోండి.',
    'compare.remove': 'తొలగించండి',
    'compare.addBank': 'సరిపోల్చడానికి బ్యాంక్ జోడించండి',
    'compare.chooseBank': 'బ్యాంక్ ఎంచుకోండి',
    'compare.addNbfc': 'సరిపోల్చడానికి ఓవర్ డ్రాఫ్ట్ జోడించండి',
    'compare.chooseNbfc': 'ఓవర్ డ్రాఫ్ట్ ఎంచుకోండి (బజాజ్, టాటా, మొదలైనవి)',
    'compare.noMoreBanks': 'జోడించడానికి మరింత బ్యాంకులు లేవు',
    'compare.comparison': 'సరిపోల్పు',
    'compare.parameter': 'పారామీటర్',
    'compare.monthlyEmi': 'నెలవారీ EMI',
    'compare.totalInterestPayable': 'మొత్తం వడ్డీ చెల్లించాలి',
    'compare.totalPayment': 'మొత్తం చెల్లింపు',
    'compare.processingFee': 'ప్రాసెసింగ్ ఫీజు',
    'compare.loanAmountRange': 'రుణ మొత్తం పరిధి',
    'compare.tenureRange': 'కాల పరిధి',
    'compare.description': 'వివరణ',
    'compare.keyFeatures': 'కీ ఫీచర్లు',
    'compare.apply': 'అప్లై చేయండి',
    'compare.applyWith': 'అప్లై చేయండి',
    'compare.years': 'సంవత్సరాలు',
    'cibil.heroTitle': 'ఈ రోజు మీ ఉచిత క్రెడిట్ స్కోర్ తనిఖీ చేయండి!',
    'cibil.securityMessage': 'మీ వ్యక్తిగత సమాచారం 100% సురక్షితం.',
    'cibil.formNameLabel': 'పాన్ కార్డ్ ప్రకారం పేరు',
    'cibil.formPanLabel': 'పాన్ నంబర్',
    'cibil.formDobLabel': 'పుట్టిన తేదీ',
    'cibil.formMobileLabel': 'మొబైల్ నంబర్',
    'cibil.formEmailLabel': 'ఇమెయిల్',
    'cibil.formCityLabel': 'నగరం',
    'cibil.formPincodeLabel': 'పిన్ కోడ్',
    'cibil.formSubmitting': 'సమర్పిస్తోంది...',
  } as Record<string, string>,
  ml: {
    'nav.home': 'ഹോം',
    'nav.about': 'ഞങ്ങളെക്കുറിച്ച്',
    'nav.emi': 'EMI കാൽക്കുലേറ്റർ',
    'nav.apply': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    'nav.cibil': 'സിബിൽ സ്കോർ',
    'nav.contact': 'വിദഗ്ധനോട് സംസാരിക്കുക',
    'nav.partner': 'പങ്കാളിയാകുക',
    'nav.login': 'ലോഗിൻ',
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',
    'hero.title': 'നിങ്ങളുടെ മികച്ച ജീവിതത്തിന് മികച്ച ഭാവിയെ നൽകുന്നു.',
    'hero.highlight': 'മികച്ച',
    'hero.titleLine1': 'മികച്ച ഭാവിയെ',
    'hero.titleLine2': 'നിങ്ങളുടെ മികച്ച ജീവിതത്തിന് നൽകുന്നു.',
    'features.personalPrivacy': 'വ്യക്തിഗത സ്വകാര്യത',
    'features.noPayment': 'പണം ആവശ്യമില്ല',
    'features.easyAccess': 'എളുപ്പത്തിൽ ആക്സസ്',
    'carousel.applyNow': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    'loanTiles.title': 'ഞങ്ങളുടെ ലോൺ ഉത്പന്നങ്ങൾ',
    'trust.title': 'വിശ്വാസത്തോടെ',
    'trust.titleHighlight': 'ആത്മവിശ്വാസം',
    'trust.loansDisbursed': '₹ 15000 കോടി+',
    'trust.loansDisbursedDesc': 'ഉപയോക്താക്കൾക്ക് വിതരണം ചെയ്ത ലോണുകളുടെ മൂല്യം',
    'trust.since2016': '2016 മുതൽ',
    'trust.panIndia': 'പാൻ ഇന്ത്യ',
    'testimonials.happyClients': '12K + സന്തോഷിത ക്ലയന്റുകൾ',
    'testimonials.title': 'ക്ലയന്റ് അനുഭവങ്ങൾ',
    'testimonials.readAll': 'എല്ലാ അവലോകനങ്ങളും വായിക്കുക →',
    'testimonials.rating': 'റേറ്റിംഗ്',
    'partners.title': 'ഞങ്ങളുടെ അംഗീകൃത പങ്കാളികൾ',
    'footer.tagline': 'പണം നേടുന്ന ഏറ്റവും വേഗത്തിലുള്ള മാർഗം',
    'footer.quickLinks': 'ക്വിക്ക് ലിങ്കുകൾ',
    'footer.getInTouch': 'ബന്ധപ്പെടുക',
    'footer.socialMedia': 'സോഷ്യൽ മീഡിയ ലിങ്കുകൾ',
    'footer.copyright': '© കോപ്പിറൈറ്റ് 2026 | HELLOANS ZINEE SERVICES PVT LTD',
    'contact.getInTouch': 'ബന്ധപ്പെടുക',
    'contact.talkToExpert': 'വിദഗ്ധനോട് സംസാരിക്കുക',
    'contact.chatbotIntro': 'ലോണുകളെക്കുറിച്ച് ചോദ്യങ്ങൾ ഉണ്ടോ? ഫോം ഇല്ലാതെ ഞങ്ങളുടെ വിദഗ്ധനുമായി ചാറ്റ് ആരംഭിക്കുക.',
    'contact.chatbotDesc': 'ലോൺ തരങ്ങൾ, യോഗ്യത, ഡോക്യുമെന്റുകൾ സഹായിക്കും; ടീമുമായി കണക്ട് ചെയ്യാം.',
    'contact.startChat': 'ചാറ്റ് ആരംഭിക്കുക',
    'contact.name': 'പേര്',
    'contact.email': 'ഇമെയിൽ',
    'contact.phone': 'ഫോൺ',
    'contact.message': 'സന്ദേശം',
    'contact.submit': 'സമർപ്പിക്കുക',
    'contact.submitting': 'സമർപ്പിക്കുന്നു...',
    'partner.title': 'പങ്കാളിയാകുക',
    'partner.titlePrefix': '',
    'partner.titleHighlight': 'പങ്കാളിയാകുക',
    'partner.titleSuffix': '',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'ലോൺ നൽകുന്നവരുടെ നെറ്റ്‌വർക്കിൽ ചേരുക, നിങ്ങളുടെ ബിസിനസ് വളർത്തുക.',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'നിങ്ങളുടെ പേര്',
    'partner.labelFullName': 'Full name',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.labelWorkEmail': 'Work email',
    'partner.labelPhone': 'Contact number',
    'partner.labelCity': 'City',
    'partner.labelTellUsMore': 'How do you want to partner?',
    'partner.companyName': 'കമ്പനി പേര്',
    'partner.email': 'ഇമെയിൽ',
    'partner.phone': 'ഫോൺ നമ്പർ',
    'partner.city': 'നഗരം',
    'partner.message': 'സന്ദേശം',
    'partner.submit': 'അഭ്യർത്ഥന സമർപ്പിക്കുക',
    'partner.submitting': 'സമർപ്പിക്കുന്നു...',
    'partner.success': 'അപേക്ഷ വിജയകരമായി സമർപ്പിച്ചു! ഉടൻ ബന്ധപ്പെടും.',
    'partner.error': 'എന്തോ തെറ്റുപോയി. വീണ്ടും ശ്രമിക്കുക.',
    'partner.benefitsHeading': 'Helloans പങ്കാളിയാകുന്നതിന്റെ പ്രയോജനങ്ങൾ',
    'partner.benefit1': 'ലോൺ ഉൽപ്പന്നങ്ങൾക്കും കടം നൽകുന്നവർക്കും വിപുലമായ ആക്സസ്',
    'partner.benefit2': 'നിങ്ങളുടെ ടീമിനായി സമർപ്പിത പിന്തുണയും പരിശീലനവും',
    'partner.benefit3': 'മത്സര കമ്മീഷനും സമയം അനുസരിച്ചുള്ള പേ outട്ടുകളും',
    'partner.benefit4': 'മാർക്കറ്റിംഗും ലീഡ് ജനറേഷൻ പിന്തുണയും',
    'partner.benefit5': 'വിശ്വസനീയമായ ബ്രാൻഡിനൊപ്പം നിങ്ങളുടെ ബിസിനസ് വളർത്തുക',
    'about.title': 'ഞങ്ങളെക്കുറിച്ച്',
    'about.subtitle': 'വ്യക്തികൾക്കും ബിസിനസുകൾക്കും ഇഷ്ടാനുസൃത ലോൺ നൽകുന്നതിൽ ഞങ്ങൾ വിദഗ്ധരാണ്.',
    'about.learnMore': 'കൂടുതൽ അറിയുക →',
    'about.gallery': 'ഗാലറി',
    'emi.pageTitle': 'EMI കാൽക്കുലേറ്റർ',
    'emi.pageDesc': 'ലോൺ തുക, പലിശ നിരക്ക്, കാലാവധി നൽകുക; പ്രതിമാസ EMI, മൊത്തം പലിശ, മൊത്തം തിരിച്ചടവ് ഉടൻ കാണുക.',
    'emi.calculateYour': 'കണക്കാക്കുക',
    'emi.loanAmount': 'ലോൺ തുക',
    'emi.rateOfInterest': 'പലിശ നിരക്ക് (വാർഷികം)',
    'emi.loanTenure': 'ലോൺ കാലാവധി',
    'emi.loanEmi': 'ലോൺ EMI',
    'emi.totalInterestPayable': 'മൊത്തം പലിശ അടയ്ക്കേണ്ടത്',
    'emi.totalPayment': 'മൊത്തം തിരിച്ചടവ് (മുതൽ + പലിശ)',
    'emi.principalAmount': 'മുതൽ തുക',
    'emi.totalInterest': 'മൊത്തം പലിശ',
    'emi.yr': 'വർഷം',
    'emi.mo': 'മാസം',
    'apply.title': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    'apply.intro': 'മത്സര പലിശ നിരക്കുകളോടെ തൽക്ഷണ ലോൺ അനുമതി നേടുക! ഫോം പൂരിപ്പിക്കുക, 24 മണിക്കൂറിനുള്ളിൽ ഞങ്ങളുടെ ടീം ബന്ധപ്പെടും.',
    'apply.quickApproval': 'വേഗത്തിലുള്ള അനുമതി',
    'apply.lowInterestRates': 'കുറഞ്ഞ പലിശ നിരക്കുകൾ',
    'apply.minimalDoc': 'കുറഞ്ഞ ഡോക്യുമെന്റേഷൻ',
    'apply.flexibleRepayment': 'ഫ്ലെക്സിബിൾ തിരിച്ചടവ്',
    'apply.callUsDirectly': 'നേരിട്ട് കോൾ ചെയ്യുക',
    'apply.talkToExpert': 'വിദഗ്ധനോട് സംസാരിക്കുക',
    'apply.chatWithTeam': 'ഞങ്ങളുടെ ടീമുമായി ചാറ്റ് ചെയ്യുക',
    'apply.personalInfo': 'വ്യക്തിഗത വിവരങ്ങൾ',
    'apply.fullName': 'പൂർണ്ണ പേര്',
    'apply.enterFullName': 'നിങ്ങളുടെ പൂർണ്ണ പേര് നൽകുക',
    'apply.emailAddress': 'ഇമെയിൽ വിലാസം',
    'apply.phoneNumber': 'ഫോൺ നമ്പർ',
    'apply.enterPhone': '10 അക്ക മൊബൈൽ നമ്പർ',
    'apply.city': 'നഗരം',
    'apply.enterCity': 'നിങ്ങളുടെ നഗരം നൽകുക',
    'apply.pincode': 'പിൻകോഡ്',
    'apply.pincodePlaceholder': '6 അക്ക പിൻകോഡ്',
    'apply.tellUsAbout': 'നിങ്ങളുടെ ലോൺ ആവശ്യങ്ങളെക്കുറിച്ച് പറയുക',
    'apply.submitting': 'സമർപ്പിക്കുന്നു...',
    'apply.applyNow': 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    'apply.applyNowLine1': 'അപേക്ഷിക്കുക',
    'apply.applyNowLine2': 'ഇപ്പോൾ',
    'apply.successMessage': 'വിജയം! നിങ്ങളുടെ ലോൺ അപേക്ഷ സമർപ്പിച്ചു. 24 മണിക്കൂറിനുള്ളിൽ ഞങ്ങളുടെ ടീം ബന്ധപ്പെടും.',
    'apply.errorMessage': 'അപേക്ഷ സമർപ്പിക്കുന്നതിൽ പിശക്. വീണ്ടും ശ്രമിക്കുക.',
    'reviews.title': 'എല്ലാ അവലോകനങ്ങളും',
    'reviews.intro': 'ഞങ്ങളുടെ ക്ലയന്റുകൾ ഞങ്ങളെക്കുറിച്ച് എന്താണ് പറയുന്നത് വായിക്കുക',
    'reviews.allReviews': 'എല്ലാ ക്ലയന്റ് അവലോകനങ്ങളും',
    'reviews.happyClients': '12K + സന്തോഷിത ക്ലയന്റുകൾ',
    'reviews.thankYou': 'നന്ദി! നിങ്ങളുടെ അവലോകനം വിജയകരമായി സമർപ്പിച്ചു.',
    'reviews.errorMessage': 'അവലോകനം സമർപ്പിക്കുന്നതിൽ പിശക്. വീണ്ടും ശ്രമിക്കുക.',
    'reviews.writeReview': 'അവലോകനം എഴുതുക',
    'reviews.shareExperience': 'ഞങ്ങളോടൊപ്പം നിങ്ങളുടെ അനുഭവം പങ്കിടുക',
    'reviews.yourName': 'നിങ്ങളുടെ പേര്',
    'reviews.yourEmail': 'നിങ്ങളുടെ ഇമെയിൽ',
    'reviews.yourReview': 'നിങ്ങളുടെ അവലോകനം ഇവിടെ എഴുതുക...',
    'reviews.submitReview': 'അവലോകനം സമർപ്പിക്കുക',
    'reviews.ratingOption': 'റേറ്റിംഗ്',
    'compare.title': 'താരതമ്യം ചെയ്യുക വ്യക്തിഗത ലോണുകൾ മറ്റും ഓവർ ഡ്രാഫ്റ്റ്',
    'compare.subtitle': 'EMI, പലിശ, ഫീസ്, ഫീച്ചറുകൾ പാർശ്വത്ത് താരതമ്യം ചെയ്യാൻ 3 ബാങ്കുകൾ തിരഞ്ഞെടുക്കുക.',
    'compare.remove': 'നീക്കം ചെയ്യുക',
    'compare.addBank': 'താരതമ്യം ചെയ്യാൻ ബാങ്ക് ചേർക്കുക',
    'compare.chooseBank': 'ബാങ്ക് തിരഞ്ഞെടുക്കുക',
    'compare.addNbfc': 'താരതമ്യം ചെയ്യാൻ ഓവർ ഡ്രാഫ്റ്റ് ചേർക്കുക',
    'compare.chooseNbfc': 'ഓവർ ഡ്രാഫ്റ്റ് തിരഞ്ഞെടുക്കുക (ബജാജ്, ടാറ്റാ മുതലായവ)',
    'compare.noMoreBanks': 'ചേർക്കാൻ കൂടുതൽ ബാങ്കുകൾ ഇല്ല',
    'compare.comparison': 'താരതമ്യം',
    'compare.parameter': 'പാരാമീറ്റർ',
    'compare.monthlyEmi': 'പ്രതിമാസ EMI',
    'compare.totalInterestPayable': 'മൊത്തം പലിശ അടയ്ക്കേണ്ടത്',
    'compare.totalPayment': 'മൊത്തം തിരിച്ചടവ്',
    'compare.processingFee': 'പ്രോസസ്സിംഗ് ഫീസ്',
    'compare.loanAmountRange': 'ലോൺ തുക പരിധി',
    'compare.tenureRange': 'കാലാവധി പരിധി',
    'compare.description': 'വിവരണം',
    'compare.keyFeatures': 'കീ ഫീച്ചറുകൾ',
    'compare.apply': 'അപേക്ഷിക്കുക',
    'compare.applyWith': 'അപേക്ഷിക്കുക',
    'compare.years': 'വർഷങ്ങൾ',
    'cibil.heroTitle': 'ഇന്ന് നിങ്ങളുടെ സൗജന്യ ക്രെഡിറ്റ് സ്കോർ പരിശോധിക്കുക!',
    'cibil.securityMessage': 'നിങ്ങളുടെ വ്യക്തിഗത വിവരങ്ങൾ 100% സുരക്ഷിതം.',
    'cibil.formNameLabel': 'പാൻ കാർഡ് പോലെ പേര്',
    'cibil.formPanLabel': 'പാൻ നമ്പർ',
    'cibil.formDobLabel': 'ജനന തീയതി',
    'cibil.formMobileLabel': 'മൊബൈൽ നമ്പർ',
    'cibil.formEmailLabel': 'ഇമെയിൽ',
    'cibil.formCityLabel': 'നഗരം',
    'cibil.formPincodeLabel': 'പിൻകോഡ്',
    'cibil.formSubmitting': 'സമർപ്പിക്കുന്നു...',
  } as Record<string, string>,
  kn: {
    'nav.home': 'ಮುಖಪುಟ',
    'nav.about': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'nav.emi': 'EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    'nav.apply': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'nav.cibil': 'ಸಿಬಿಲ್ ಸ್ಕೋರ್',
    'nav.contact': 'ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    'nav.partner': 'ಪಾಲುದಾರರಾಗಿ',
    'nav.login': 'ಲಾಗಿನ್',
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.tamil': 'தமிழ்',
    'lang.telugu': 'తెలుగు',
    'lang.malayalam': 'മലയാളം',
    'lang.kannada': 'ಕನ್ನಡ',
    'hero.title': 'ನಿಮ್ಮ ಉತ್ತಮ ಜೀವನಕ್ಕಾಗಿ ಉತ್ತಮ ಭವಿಷ್ಯವನ್ನು ಒದಗಿಸುವುದು.',
    'hero.highlight': 'ಉತ್ತಮ',
    'hero.titleLine1': 'ಉತ್ತಮ ಭವಿಷ್ಯವನ್ನು',
    'hero.titleLine2': 'ನಿಮ್ಮ ಉತ್ತಮ ಜೀವನಕ್ಕಾಗಿ ಒದಗಿಸುತ್ತಿದ್ದೇವೆ.',
    'features.personalPrivacy': 'ವೈಯಕ್ತಿಕ ಗೌಪ್ಯತೆ',
    'features.noPayment': 'ಪಾವತಿ ಅಗತ್ಯವಿಲ್ಲ',
    'features.easyAccess': 'ಸುಲಭ ಪ್ರವೇಶ',
    'carousel.applyNow': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'loanTiles.title': 'ನಮ್ಮ ಲೋನ್ ಉತ್ಪನ್ನಗಳು',
    'trust.title': 'ವಿಶ್ವಾಸದಿಂದ',
    'trust.titleHighlight': 'ಆತ್ಮವಿಶ್ವಾಸ',
    'trust.loansDisbursed': '₹ 15000 ಕೋಟಿ+',
    'trust.loansDisbursedDesc': 'ಬಳಕೆದಾರರಿಗೆ ವಿತರಿಸಿದ ಲೋನ್‌ಗಳ ಮೌಲ್ಯ',
    'trust.since2016': '2016 ರಿಂದ',
    'trust.panIndia': 'ಪ್ಯಾನ್ ಇಂಡಿಯಾ',
    'testimonials.happyClients': '12K + ಸಂತೋಷಿತ ಗ್ರಾಹಕರು',
    'testimonials.title': 'ಗ್ರಾಹಕ ಅನುಭವಗಳು',
    'testimonials.readAll': 'ಎಲ್ಲಾ ವಿಮರ್ಶೆಗಳನ್ನು ಓದಿ →',
    'testimonials.rating': 'ರೇಟಿಂಗ್',
    'partners.title': 'ನಮ್ಮ ಅಧಿಕೃತ ಪಾಲುದಾರರು',
    'footer.tagline': 'ಹಣ ಪಡೆಯಲು ಅತ್ಯಂತ ವೇಗದ ಮಾರ್ಗ',
    'footer.quickLinks': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    'footer.getInTouch': 'ಸಂಪರ್ಕಿಸಿ',
    'footer.socialMedia': 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಲಿಂಕ್‌ಗಳು',
    'footer.copyright': '© ಕೃತಿಸ್ವಾಮ್ಯ 2026 | HELLOANS ZINEE SERVICES PVT LTD',
    'contact.getInTouch': 'ಸಂಪರ್ಕಿಸಿ',
    'contact.talkToExpert': 'ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    'contact.chatbotIntro': 'ಸಾಲಗಳ ಕುರಿತು ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ? ಫಾರಮ್ ಇಲ್ಲದೆ ನಮ್ಮ ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ.',
    'contact.chatbotDesc': 'ಸಾಲ ಪ್ರಕಾರಗಳು, ಅರ್ಹತೆ, ಡಾಕ್ಯುಮೆಂಟ್ಗಳು ಸಹಾಯ ಮತ್ತು ತಂಡಕ್ಕೆ ಸಂಪರ್ಕಿಸಿ.',
    'contact.startChat': 'ಚಾಟ್ ಪ್ರಾರಂಭಿಸಿ',
    'contact.name': 'ಹೆಸರು',
    'contact.email': 'ಇಮೇಲ್',
    'contact.phone': 'ಫೋನ್',
    'contact.message': 'ಸಂದೇಶ',
    'contact.submit': 'ಸಲ್ಲಿಸಿ',
    'contact.submitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'partner.title': 'ಪಾಲುದಾರರಾಗಿ',
    'partner.titlePrefix': '',
    'partner.titleHighlight': 'ಪಾಲುದಾರರಾಗಿ',
    'partner.titleSuffix': '',
    'partner.heroTagline': 'Partner with Helloans — grow your distribution, multiply your reach.',
    'partner.subtitle': 'ಲೋನ್ ಒದಗಿಸುವವರ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ, ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಬೆಳೆಸಿ.',
    'partner.sectionYourDetails': 'Your details',
    'partner.sectionBusiness': 'Business details',
    'partner.sectionGoals': 'Tell us your goals',
    'partner.name': 'ನಿಮ್ಮ ಹೆಸರು',
    'partner.labelFullName': 'Full name',
    'partner.labelCompanyOrBusiness': 'Company or business name',
    'partner.labelWorkEmail': 'Work email',
    'partner.labelPhone': 'Contact number',
    'partner.labelCity': 'City',
    'partner.labelTellUsMore': 'How do you want to partner?',
    'partner.companyName': 'ಕಂಪನಿ ಹೆಸರು',
    'partner.email': 'ಇಮೇಲ್',
    'partner.phone': 'ಫೋನ್ ನಂಬರ್',
    'partner.city': 'ನಗರ',
    'partner.message': 'ಸಂದೇಶ',
    'partner.submit': 'ವಿನಂತಿ ಸಲ್ಲಿಸಿ',
    'partner.submitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'partner.success': 'ಅರ್ಜಿ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಯಿತು! ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    'partner.error': 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'partner.benefitsHeading': 'Helloans ಪಾಲುದಾರರಾಗುವ ಲಾಭಗಳು',
    'partner.benefit1': 'ಸಾಲ ಉತ್ಪನ್ನಗಳು ಮತ್ತು ಸಾಲದಾತರಿಗೆ ವ್ಯಾಪಕ ಪ್ರವೇಶ',
    'partner.benefit2': 'ನಿಮ್ಮ ತಂಡಕ್ಕೆ ಸಮರ್ಪಿತ ಬೆಂಬಲ ಮತ್ತು ತರಬೇತಿ',
    'partner.benefit3': 'ಸ್ಪರ್ಧಾತ್ಮಕ ಕಮಿಷನ್ ಮತ್ತು ಸಕಾಲಿಕ ಪಾವತಿಗಳು',
    'partner.benefit4': 'ಮಾರ್ಕೆಟಿಂಗ್ ಮತ್ತು ಲೀಡ್ ಜನರೇಷನ್ ಬೆಂಬಲ',
    'partner.benefit5': 'ವಿಶ್ವಾಸಾರ್ಹ ಬ್ರಾಂಡ್ ನೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಬೆಳೆಯಿರಿ',
    'about.title': 'ನಮ್ಮ ಬಗ್ಗೆ',
    'about.subtitle': 'ವ್ಯಕ್ತಿಗಳು ಮತ್ತು ವ್ಯಾಪಾರಗಳಿಗೆ ಕಸ್ಟಮೈಸ್ಡ್ ಲೋನ್‌ನಲ್ಲಿ ನಾವು ಪರಿಣತಿ ಹೊಂದಿದ್ದೇವೆ.',
    'about.learnMore': 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ →',
    'about.gallery': 'ಗ್ಯಾಲರಿ',
    'emi.pageTitle': 'EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    'emi.pageDesc': 'ಲೋನ್ ಮೊತ್ತ, ಬಡ್ಡಿ ದರ ಮತ್ತು ಅವಧಿ ನಮೂದಿಸಿ; ಮಾಸಿಕ EMI, ಒಟ್ಟು ಬಡ್ಡಿ ಮತ್ತು ಒಟ್ಟು ಪಾವತಿಯನ್ನು ತಕ್ಷಣ ನೋಡಿ.',
    'emi.calculateYour': 'ಲೆಕ್ಕ ಹಾಕಿ',
    'emi.loanAmount': 'ಲೋನ್ ಮೊತ್ತ',
    'emi.rateOfInterest': 'ಬಡ್ಡಿ ದರ (ವಾರ್ಷಿಕ)',
    'emi.loanTenure': 'ಲೋನ್ ಅವಧಿ',
    'emi.loanEmi': 'ಲೋನ್ EMI',
    'emi.totalInterestPayable': 'ಒಟ್ಟು ಬಡ್ಡಿ ಪಾವತಿಸಬೇಕು',
    'emi.totalPayment': 'ಒಟ್ಟು ಪಾವತಿ (ಮುಧ್ಯ + ಬಡ್ಡಿ)',
    'emi.principalAmount': 'ಮುಧ್ಯ ಮೊತ್ತ',
    'emi.totalInterest': 'ಒಟ್ಟು ಬಡ್ಡಿ',
    'emi.yr': 'ವರ್ಷ',
    'emi.mo': 'ತಿಂಗಳು',
    'apply.title': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'apply.intro': 'ಸ್ಪರ್ಧಾತ್ಮಕ ಬಡ್ಡಿ ದರಗಳೊಂದಿಗೆ ತ್ವರಿತ ಲೋನ್ ಅನುಮೋದನೆ ಪಡೆಯಿರಿ! ಫಾರಂ ಪೂರೈಸಿ, 24 ಗಂಟೆಗಳಲ್ಲಿ ನಮ್ಮ ತಂಡ ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    'apply.quickApproval': 'ತ್ವರಿತ ಅನುಮೋದನೆ',
    'apply.lowInterestRates': 'ಕಡಿಮೆ ಬಡ್ಡಿ ದರಗಳು',
    'apply.minimalDoc': 'ಕನಿಷ್ಠ ಡಾಕ್ಯುಮೆಂಟೇಷನ್',
    'apply.flexibleRepayment': 'ನಮ್ಯ ಮರುಪಾವತಿ',
    'apply.callUsDirectly': 'ನೇರವಾಗಿ ಕರೆ ಮಾಡಿ',
    'apply.talkToExpert': 'ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ',
    'apply.chatWithTeam': 'ನಮ್ಮ ತಂಡದೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ',
    'apply.personalInfo': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'apply.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'apply.enterFullName': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    'apply.emailAddress': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'apply.phoneNumber': 'ಫೋನ್ ನಂಬರ್',
    'apply.enterPhone': '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ನಂಬರ್',
    'apply.city': 'ನಗರ',
    'apply.enterCity': 'ನಿಮ್ಮ ನಗರ ನಮೂದಿಸಿ',
    'apply.pincode': 'ಪಿನ್ ಕೋಡ್',
    'apply.pincodePlaceholder': '6 ಅಂಕಿಯ ಪಿನ್ ಕೋಡ್',
    'apply.tellUsAbout': 'ನಿಮ್ಮ ಲೋನ್ ಅಗತ್ಯಗಳ ಬಗ್ಗೆ ಹೇಳಿ',
    'apply.submitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'apply.applyNow': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'apply.applyNowLine1': 'ಅರ್ಜಿ',
    'apply.applyNowLine2': 'ಈಗ',
    'apply.successMessage': 'ಯಶಸ್ಸು! ನಿಮ್ಮ ಲೋನ್ ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಯಿತು. 24 ಗಂಟೆಗಳಲ್ಲಿ ನಮ್ಮ ತಂಡ ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    'apply.errorMessage': 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವಲ್ಲಿ ದೋಷ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'reviews.title': 'ಎಲ್ಲಾ ವಿಮರ್ಶೆಗಳು',
    'reviews.intro': 'ನಮ್ಮ ಗ್ರಾಹಕರು ನಮ್ಮ ಬಗ್ಗೆ ಏನು ಹೇಳುತ್ತಾರೆ ಓದಿ',
    'reviews.allReviews': 'ಎಲ್ಲಾ ಗ್ರಾಹಕ ವಿಮರ್ಶೆಗಳು',
    'reviews.happyClients': '12K + ಸಂತೋಷಿತ ಗ್ರಾಹಕರು',
    'reviews.thankYou': 'ಧನ್ಯವಾದ! ನಿಮ್ಮ ವಿಮರ್ಶೆ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಯಿತು.',
    'reviews.errorMessage': 'ವಿಮರ್ಶೆ ಸಲ್ಲಿಸುವಲ್ಲಿ ದೋಷ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'reviews.writeReview': 'ವಿಮರ್ಶೆ ಬರೆಯಿರಿ',
    'reviews.shareExperience': 'ನಮ್ಮೊಂದಿಗೆ ನಿಮ್ಮ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    'reviews.yourName': 'ನಿಮ್ಮ ಹೆಸರು',
    'reviews.yourEmail': 'ನಿಮ್ಮ ಇಮೇಲ್',
    'reviews.yourReview': 'ನಿಮ್ಮ ವಿಮರ್ಶೆ ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
    'reviews.submitReview': 'ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ',
    'reviews.ratingOption': 'ರೇಟಿಂಗ್',
    'compare.title': 'ಹೋಲಿಸಿ ವೈಯಕ್ತಿಕ ಸಾಲಗಳು ಮತ್ತು ಓವರ್ ಡ್ರಾಫ್ಟ್',
    'compare.subtitle': 'EMI, ಬಡ್ಡಿ, ಫೀಸ್ ಮತ್ತು ಫೀಚರ್‌ಗಳನ್ನು ಪಕ್ಕಪಕ್ಕದಲ್ಲಿ ಹೋಲಿಸಲು 3 ಬ್ಯಾಂಕ್‌ಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'compare.remove': 'ತೆಗೆದುಹಾಕಿ',
    'compare.addBank': 'ಹೋಲಿಸಲು ಬ್ಯಾಂಕ್ ಸೇರಿಸಿ',
    'compare.chooseBank': 'ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ',
    'compare.addNbfc': 'ಹೋಲಿಸಲು ಓವರ್ ಡ್ರಾಫ್ಟ್ ಸೇರಿಸಿ',
    'compare.chooseNbfc': 'ಓವರ್ ಡ್ರಾಫ್ಟ್ ಆಯ್ಕೆಮಾಡಿ (ಬಜಾಜ್, ಟಾಟಾ, ಇತ್ಯಾದಿ)',
    'compare.noMoreBanks': 'ಸೇರಿಸಲು ಹೆಚ್ಚಿನ ಬ್ಯಾಂಕ್‌ಗಳಿಲ್ಲ',
    'compare.comparison': 'ಹೋಲಿಕೆ',
    'compare.parameter': 'ಪ್ಯಾರಾಮೀಟರ್',
    'compare.monthlyEmi': 'ಮಾಸಿಕ EMI',
    'compare.totalInterestPayable': 'ಒಟ್ಟು ಬಡ್ಡಿ ಪಾವತಿಸಬೇಕು',
    'compare.totalPayment': 'ಒಟ್ಟು ಪಾವತಿ',
    'compare.processingFee': 'ಪ್ರೊಸೆಸಿಂಗ್ ಫೀಸ್',
    'compare.loanAmountRange': 'ಲೋನ್ ಮೊತ್ತ ಶ್ರೇಣಿ',
    'compare.tenureRange': 'ಅವಧಿ ಶ್ರೇಣಿ',
    'compare.description': 'ವಿವರಣೆ',
    'compare.keyFeatures': 'ಮುಖ್ಯ ಲಕ್ಷಣಗಳು',
    'compare.apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'compare.applyWith': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'compare.years': 'ವರ್ಷಗಳು',
    'cibil.heroTitle': 'ಇಂದು ನಿಮ್ಮ ಉಚಿತ ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್ ಪರಿಶೀಲಿಸಿ!',
    'cibil.securityMessage': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ 100% ಸುರಕ್ಷಿತವಾಗಿದೆ.',
    'cibil.formNameLabel': 'ಪ್ಯಾನ್ ಕಾರ್ಡ್ ಪ್ರಕಾರ ಹೆಸರು',
    'cibil.formPanLabel': 'ಪ್ಯಾನ್ ನಂಬರ್',
    'cibil.formDobLabel': 'ಜನ್ಮ ದಿನಾಂಕ',
    'cibil.formMobileLabel': 'ಮೊಬೈಲ್ ನಂಬರ್',
    'cibil.formEmailLabel': 'ಇಮೇಲ್',
    'cibil.formCityLabel': 'ನಗರ',
    'cibil.formPincodeLabel': 'ಪಿನ್ ಕೋಡ್',
    'cibil.formSubmitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
  } as Record<string, string>,
}

const langLabelKeys: Record<Language, string> = {
  en: 'lang.english',
  hi: 'lang.hindi',
  ta: 'lang.tamil',
  te: 'lang.telugu',
  ml: 'lang.malayalam',
  kn: 'lang.kannada',
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (SUPPORTED_LANGUAGES.includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    const langMap = translations as Record<Language, Record<string, string>>
    const fallback = langMap.en?.[key]
    return langMap[language]?.[key] ?? fallback ?? key
  }

  useEffect(() => {
    // Update HTML lang attribute when language changes
    document.documentElement.lang = language
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, supportedLanguages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function getLangLabelKey(lang: Language): string {
  return langLabelKeys[lang] ?? 'lang.english'
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
